Feature/si 884 add hook to get provider currentchain and mainnetprovider
lidofinance/ethereum-staking-widget pull request #101
Opened 2023-10-18 20:47 UTC by solidovic

### Description

### Demo

### Code review notes

### Testing notes

### Checklist:

- [ ] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-10-19 10:18 UTC, Jeday requested changes

2023-10-19 10:18 UTC, Jeday commented on config/rpc.ts
> +// export const getRpcUrl = (): string => {
No commented code. Just delete. We have git history.

2023-10-19 10:18 UTC, Jeday commented on config/rpc.ts
> +export const useRpcUrlByChainIdGetter = () => {
Why getter? That's just a hook.

2023-10-19 10:18 UTC, Jeday commented on config/rpc.ts
> +export const useRpcUrlByChainIdGetter = () => {
For non react runtime, naming would be getRpcUrl...

2023-10-19 10:18 UTC, Jeday commented on features/ipfs/ipfs-info-box/ipfs-info-box.tsx
> +      // TODO
specify TODO so that others can pick up later

2023-10-19 10:18 UTC, Jeday commented on providers/custom-config.tsx
> +// export const getRestoredSettings = () => {
delete comments

2023-10-19 10:18 UTC, Jeday commented on providers/web3.tsx
> +          // TODO
what TODO?

2023-10-19 10:18 UTC, Jeday commented on providers/web3.tsx
> +        // TODO
what TODO

2023-10-19 10:18 UTC, Jeday commented on providers/web3.tsx
> +          // TODO
what TODO

2023-10-19 10:18 UTC, Jeday commented on shared/hooks/use-current-static-rpc-provider.ts
> +    // TODO
what TODO

2023-10-19 20:15 UTC, solidovic commented on config/rpc.ts
> +// export const getRpcUrl = (): string => {
removed

2023-10-19 20:23 UTC, solidovic commented on config/rpc.ts
> +export const useRpcUrlByChainIdGetter = () => {
logically, but 2 verbs step by step not beautiful and bad readable.
reverted and set TODO.

2023-10-19 20:23 UTC, solidovic commented on features/ipfs/ipfs-info-box/ipfs-info-box.tsx
> +      // TODO
remove

2023-10-19 20:23 UTC, solidovic commented on providers/custom-config.tsx
> +// export const getRestoredSettings = () => {
remove

2023-10-19 20:23 UTC, solidovic commented on providers/web3.tsx
> +          // TODO
remove

2023-10-19 20:23 UTC, solidovic commented on providers/web3.tsx
> +        // TODO
remove

2023-10-19 20:23 UTC, solidovic commented on providers/web3.tsx
> +          // TODO
remove

2023-10-19 20:23 UTC, solidovic commented on shared/hooks/use-current-static-rpc-provider.ts
> +    // TODO
remove

2023-10-20 05:35 UTC, Jeday approved these changes

2023-10-20 05:57 UTC, DiRaiks commented on config/rpc.ts
> +  return getRpcUrlByChainId(chainId as unknown as CHAINS);
`as number` is enough

2023-10-20 05:58 UTC, DiRaiks commented on features/home/stake-form/stake-form.tsx
> +
unnecessary empty string

2023-10-20 05:59 UTC, DiRaiks commented on features/home/stake-form/stake-form.tsx
> +import { OneinchInfo } from 'features/home/oneinch-info/oneinch-info';
Is not used in this file

2023-10-20 06:02 UTC, DiRaiks commented on features/rewards/components/stats/Stats.tsx
> +  }, [mainnetStaticRpcProvider]);
mainnetStaticRpcProvider is cached?

2023-10-20 06:02 UTC, DiRaiks commented on features/home/stake-form/stake-form.tsx
> +      staticRpcProvider,
staticRpcProvider is cached?

2023-10-20 06:04 UTC, DiRaiks commented on features/withdrawals/hooks/contract/useRequest.ts
> +      invariant(providerWeb3, 'must have providerWeb3');
I don't see providerWeb3 being used in this function

2023-10-20 06:05 UTC, DiRaiks commented on features/withdrawals/hooks/contract/useRequest.ts
> +      invariant(providerWeb3, 'must have providerWeb3');
I don't see providerWeb3 being used in this function

2023-10-20 08:42 UTC, solidovic commented on features/home/stake-form/stake-form.tsx
> +
many imports. wants grouped

2023-10-20 08:43 UTC, solidovic commented on features/rewards/components/stats/Stats.tsx
> +  }, [mainnetStaticRpcProvider]);
added useMemo to useCurrentStaticRpcProvider and useMainnetStaticRpcProvider

2023-10-20 08:43 UTC, solidovic commented on features/home/stake-form/stake-form.tsx
> +      staticRpcProvider,
added useMemo to useCurrentStaticRpcProvider and useMainnetStaticRpcProvider

2023-10-20 08:47 UTC, solidovic commented on features/withdrawals/hooks/contract/useRequest.ts
> +      invariant(providerWeb3, 'must have providerWeb3');
removed

2023-10-20 08:48 UTC, solidovic commented on features/withdrawals/hooks/contract/useRequest.ts
> +      invariant(providerWeb3, 'must have providerWeb3');
removed

2023-10-20 08:48 UTC, solidovic commented on features/home/stake-form/stake-form.tsx
> +import { OneinchInfo } from 'features/home/oneinch-info/oneinch-info';
removed

2023-10-20 08:48 UTC, solidovic commented on config/rpc.ts
> +  return getRpcUrlByChainId(chainId as unknown as CHAINS);
fixed

2023-10-20 09:38 UTC, DiRaiks approved these changes

2023-10-20 10:39 UTC, merged