feat: set a CORS and HttpMethodGuard for /api/oneinch-rate and /api/short-lido-stats
lidofinance/ethereum-staking-widget pull request #106
Opened 2023-10-24 16:58 UTC by solidovic

### Description

Set a CORS origin '*' and HttpMethodGuard 'GET' for:
- /api/oneinch-rate
- /api/short-lido-stats

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-10-25 06:06 UTC, Jeday requested changes

2023-10-25 06:06 UTC, Jeday commented on utilsApi/nextApiWrappers.ts
> +import { Histogram } from 'prom-client';
import type

2023-10-26 08:37 UTC, Jeday approved these changes

2023-10-27 08:10 UTC, DiRaiks approved these changes

2023-11-08 13:15 UTC, merged