refactor: remove 1inch directly rate from public api method and change env
lidofinance/ethereum-staking-widget pull request #113
Opened 2023-11-02 18:38 UTC by solidovic

### Description

- Changed `IPFS_WIDGET_ETH_API_BASE_PATH` → `WIDGET_API_BASE_PATH_FOR_IPFS`
- ~~Removed 1inch directly rate from public api method and change env~~

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-11-03 06:28 UTC, Jeday requested changes

2023-11-03 06:28 UTC, Jeday commented on features/withdrawals/hooks/useWithdrawalRates.ts
> +    getOneInchRate(amount),
You need to pass token. This is used to request rate for steth or wsteth depending on user choice when withdrawing.

2023-11-03 06:28 UTC, Jeday commented on features/home/one-inch-info/one-inch-info.tsx
> +  );
Please pass strategy. Otherwise defaults spam aggressively.

2023-11-03 06:28 UTC, Jeday commented on features/withdrawals/hooks/useWithdrawalRates.ts
> +      '/api/oneinch-rate',
How will this work in IPFS? We already route some requests to infra widget so lets do the same here.

2023-11-03 06:28 UTC, Jeday commented on features/home/one-inch-info/one-inch-info.tsx
> +    '/api/oneinch-rate',
Same question about IPFS mode.

2023-11-03 07:28 UTC, DiRaiks commented on pages/api/oneinch-rate.ts
> +      '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
Do you sure about changing the argument order?

2023-11-03 07:55 UTC, solidovic commented on pages/api/oneinch-rate.ts
> +      '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
yes. for old argument order the result was always returned equal to 
```
{"rate":0.99999}
```

2023-11-03 11:04 UTC, solidovic commented on features/home/one-inch-info/one-inch-info.tsx
> +  );
Done

2023-11-03 11:04 UTC, solidovic commented on features/withdrawals/hooks/useWithdrawalRates.ts
> +    getOneInchRate(amount),
Done

2023-11-03 11:05 UTC, solidovic commented on pages/api/oneinch-rate.ts
> +      '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
It (https://github.com/lidofinance/ethereum-staking-widget/pull/113#discussion_r1381253211) was incorrect comment

2023-11-03 11:19 UTC, solidovic commented on features/withdrawals/hooks/useWithdrawalRates.ts
> +      '/api/oneinch-rate',
Fixed

2023-11-03 11:19 UTC, solidovic commented on features/home/one-inch-info/one-inch-info.tsx
> +    '/api/oneinch-rate',
Fixed

2023-11-03 11:27 UTC, solidovic commented on pages/api/oneinch-rate.ts
> +      '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
Reverted

2023-11-03 12:39 UTC, Jeday approved these changes

2023-11-07 07:27 UTC, DiRaiks approved these changes

2023-11-07 10:47 UTC, merged