feat: query theme support
lidofinance/ethereum-staking-widget pull request #165
Opened 2023-12-01 15:58 UTC by manneredboor

### Description

Theme adjustment from query param `?query=light` or `?query=dark`

### Checklist:

- [x] Checked the changes locally.

2023-12-01 17:46 UTC, DiRaiks submitted a review, later dismissed

2023-12-04 06:30 UTC, Jeday submitted a review, later dismissed

2023-12-04 21:17 UTC, solidovic commented on providers/theme.tsx
> +  const queryTheme = router.query.theme;
may be should add optional chaining operator?

```
const queryTheme = router?.query?.theme;
```

2023-12-04 21:22 UTC, solidovic commented on providers/theme.tsx
> +    if (queryTheme === 'light') return ThemeName.light;
a border case but I suggest take into account the case `queryTheme = Light` or another variants

```queryTheme?.toLowerCase() ```

2023-12-06 10:29 UTC, manneredboor commented on providers/theme.tsx
> +  const queryTheme = router.query.theme;
We could do it certainly but it does not seems to be necessary according next.js typings

2023-12-06 12:34 UTC, manneredboor commented on providers/theme.tsx
> +  const queryTheme = router.query.theme;
Done it anyway

2023-12-06 13:12 UTC, solidovic submitted a review, later dismissed
Lgtm

2023-12-15 18:09 UTC, DiRaiks approved these changes

2023-12-15 18:16 UTC, DiRaiks requested changes
/rewards page crashes after reload

2023-12-18 11:29 UTC, Jeday approved these changes

2023-12-20 10:13 UTC, DiRaiks approved these changes

2024-01-10 10:09 UTC, merged