feat: new metrics to collect eth_to addresses call counters
lidofinance/ethereum-staking-widget pull request #167
Opened 2023-12-01 18:02 UTC by manneredboor

### Description

There was an idea to collect eth_call "to" addresses as metric. It would help us to identify pages where much requests happens or monitor unknown addresses.

### Demo

<img width="1986" alt="image" src="https://github.com/lidofinance/ethereum-staking-widget/assets/7289992/d1d9dc12-60eb-485c-8f32-f72032efeff7">

### Checklist:

- [x] Checked the changes locally.

2023-12-04 06:40 UTC, Jeday submitted a review, later dismissed

2023-12-04 06:40 UTC, Jeday commented on utilsApi/nextApiWrappers.ts
> +        metrics.labels({ address: call.params[0].to, referrer }).inc(1);
Can we also collect first 4 bytes from `data` as method? That would be first 8 symbols after `0x`. This way we can decode witch method is called.

2023-12-04 21:30 UTC, solidovic submitted a review, later dismissed

2023-12-08 13:54 UTC, Jeday requested changes

2023-12-08 13:54 UTC, Jeday commented on utilsApi/nextApiWrappers.ts
> +    const collectMetrics = async () => {
Can we move function definition outside because scoping a function also has overhead in JS. To avoid req,res  object being async destroyed or reused we can pass used req fields as arguments.

2023-12-08 13:54 UTC, Jeday commented on utilsApi/nextApiWrappers.ts
> +    void collectMetrics();
We need to either add .catch here or better a  try catch inside. Because unhandled rejected promises is a bad practise and can lead to process exit(I think).

2023-12-08 14:12 UTC, Jeday approved these changes

2023-12-08 14:12 UTC, DiRaiks approved these changes

2023-12-08 14:51 UTC, solidovic approved these changes

2023-12-11 11:40 UTC, merged