feat: paraswap withdrawal aggregator
lidofinance/ethereum-staking-widget pull request #208
Opened 2024-01-18 11:20 UTC by manneredboor

### Description

ParaSwap withdrawal aggregator returned

### Demo

<img width="526" alt="image" src="https://github.com/lidofinance/ethereum-staking-widget/assets/7289992/747830c2-e5be-4069-989d-218f77e3d1c2">

### Checklist:

- [x] Checked the changes locally.

2024-01-19 08:20 UTC, DiRaiks approved these changes

2024-01-19 08:27 UTC, DiRaiks requested changes
I did not find the ParaSwap URL added to the CSP trusted URLs. This must be done to avoid false positives.

2024-01-19 09:55 UTC, manneredboor commented
> I did not find the ParaSwap URL added to the CSP trusted URLs. This must be done to avoid false positives.

It was not deleted before, still here: https://github.com/lidofinance/ethereum-staking-widget/blob/feature/si-1177-return-paraswap-to-aggregators-page/utilsApi/withCSP.ts#L55 @DiRaiks

2024-01-19 10:18 UTC, DiRaiks approved these changes

2024-01-19 11:52 UTC, DiRaiks requested changes
Waiting for confirmation of ParaSwap link

2024-01-19 12:40 UTC, DiRaiks commented on features/withdrawals/request/form/options/dex-options.tsx
> +      `https://app.paraswap.io/#/${getTokenAddress(
Need change link to 
```ts
 `https://app.paraswap.io/referrer=Lido&takeSurplus=true#/${getTokenAddress(
        CHAINS.Mainnet,
        token,
      )}-ETH/${formatEther(amount)}/SELL?network=ethereum`,
 ```

2024-01-19 12:56 UTC, manneredboor commented on features/withdrawals/request/form/options/dex-options.tsx
> +      `https://app.paraswap.io/#/${getTokenAddress(
Done

2024-01-19 13:08 UTC, DiRaiks submitted a review, later dismissed

2024-01-22 10:59 UTC, jake4take approved these changes

2024-01-22 12:02 UTC, Jeday approved these changes

2024-01-22 12:08 UTC, merged