Modals refactor
lidofinance/ethereum-staking-widget pull request #227
Opened 2024-02-05 23:14 UTC by manneredboor

### Description

Modal system refactored

### Testing notes

All forms need to be tested

### Checklist:

- [x] Checked the changes locally.

2024-02-07 11:29 UTC, Jeday requested changes

2024-02-07 15:58 UTC, manneredboor commented on utils/formatBalance.ts
> +    maxDecimalDigits?: number;
Done 👌

2024-02-07 15:59 UTC, manneredboor commented on shared/transaction-modal/tx-stages-composed/tx-stage-amount-operation.tsx
> +      title={
I need it because amountEl is JSX element, it cannot be embedded to regular or interpolated string

2024-02-07 16:00 UTC, manneredboor commented on providers/modal-provider.tsx
> +  return useMemo(() => ({ openModal, closeModal }), [openModal, closeModal]);
This way would be cleaner, thank you 👌

2024-02-07 16:02 UTC, manneredboor commented on utils/delegate.ts
> +export class Delegate {
I see, I have considered renaming this to class EventSubscription. I believe the code and the new naming is compact enough to be self-explanatory so we do not need any comment here.

2024-02-07 16:06 UTC, manneredboor commented on features/withdrawals/request/transaction-modal-request/use-tx-modal-stages-request.ts
> +  const txModalStages = useMemo(
Such collections of modal shortcuts are not intended to be kept in fixed shape. It can vary from collection one to another, you can check different modal `use-tx-modal-stages-[...]`, each of them contains only that helpers that are necessary for related transaction processing. So I do not want to restrain this with such dedicated type to keep them customizable.

2024-02-12 11:36 UTC, Jeday commented on utils/delegate.ts
> +export class Delegate {
Sounds good

2024-02-12 11:51 UTC, Jeday approved these changes

2024-02-12 11:51 UTC, Jeday commented on providers/modal-provider.tsx
> +      forceUpdate();
If you are using ref and forceUpdate together, maybe you just need `useState`? Is there a particular reason for this?

2024-02-12 11:51 UTC, Jeday commented on providers/modal-provider.tsx
> +      const modalSession = Math.random();
We already have  `uuid` package as a subdep, so you can add it directly to package.json and use here for better code uuid.

2024-02-12 15:02 UTC, manneredboor commented on providers/modal-provider.tsx
> +      forceUpdate();
Actually `useState` should fit the purpose of there well, I have updated the code

2024-02-12 15:02 UTC, manneredboor commented on providers/modal-provider.tsx
> +      const modalSession = Math.random();
Done 👌

2024-02-14 09:56 UTC, Jeday submitted a review, later dismissed

2024-02-16 09:46 UTC, solidovic commented on features/stake/stake-form/hooks/use-tx-modal-stages-stake.tsx
> +  ...getGeneralTransactionModalStages(transitStage),
I saw :)

2024-02-16 11:01 UTC, Jeday submitted a review, later dismissed

2024-03-06 09:53 UTC, Jeday approved these changes

2024-03-06 13:06 UTC, merged