feat: one output for different configs
lidofinance/ethereum-staking-widget pull request #248
Opened 2024-02-26 07:32 UTC by solidovic

### Description

TODO...

### Code review notes

TODO...

### Testing notes

The widget must to be checked completely

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [x] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-02-27 12:50 UTC, Jeday commented on config/user-config/provider.tsx
> +export const UserConfigProvider = ({ children }: PropsWithChildren) => {
I understand why this is separate right now and not sure if we should do this in this interation. But let's consider how config could be merged together on interface level. Where code that consumes values from config is not aware is it dynamic or not, just calls hook(for react) or function (for non react).

2024-02-28 06:36 UTC, solidovic commented on config/get-config.ts
> +export const getConfig = (): any => {
You said absolutely correct! But look likes config can be changed in runtime near future ((1) banners data or (2) settings from smart-contract). Another question will be (1) (2) in `getConfig()` or another entity?

2024-02-28 06:52 UTC, solidovic commented on config/provider.tsx
> +  const contextValue = getConfig();
I agree. In current implementation the 'getConfig()' is more than enough.
But, It was made according to 'config can be changed in runtime' (https://github.com/lidofinance/ethereum-staking-widget/pull/248#discussion_r1505429210).

And I not agree with '...where dynamic config is stored outside of react...'. We use React as base, from here we should use full-React power.
Of course we can store config outside of React, but subscribes/perform to updates (reactivity) not by React looks like 'we inject reactivity inside reactivity so that you can use reactivity when you use reactivity' - I think will be more issues than benefits.

2024-02-28 06:57 UTC, solidovic commented on next.config.mjs
> +const basePath = process.env.BASE_PATH ?? '';
If process.env.BASE_PATH will be undefined `next.config.mjs` will ignore in `publicRuntimeConfig` and `serverRuntimeConfig`

2024-02-28 06:59 UTC, solidovic commented on next.config.mjs
> +  publicRuntimeConfig: {
Yes, it does. We should pass `basePath` to back and front side.
Maybe have we another way?

2024-02-28 07:00 UTC, solidovic commented on utilsApi/rpcUrls.ts
> +const { rpcUrls_1, rpcUrls_5, rpcUrls_17000 } = getConfig();
Just we will add `getServerConfig()`

2024-02-28 07:08 UTC, solidovic commented on config/user-config/provider.tsx
> +export const UserConfigProvider = ({ children }: PropsWithChildren) => {
Not sure that `config/user-config`, `config/rpc`, `config/csp` should be merged on interface level, also `banners data` and `settings from smart-contract` (see: https://github.com/lidofinance/ethereum-staking-widget/pull/248#discussion_r1505429210) - functionality (and source code) may vary greatly.

Do you have arguments?

2024-03-06 10:25 UTC, Jeday requested changes

2024-03-06 10:25 UTC, Jeday commented on config/csp/index.ts
> +const reportOnly = secretConfig.cspReportOnly == 'true';
let's cast this to boolean when it is assigned to secretConfig

2024-03-06 10:25 UTC, Jeday commented on providers/index.tsx
>      <UserConfigProvider>
I think, we can merge Config,UserConfig and Feature flag provider as one context. We won't have more rerenders as this context does not change too often. But we will debloat code. Keep the hooks separate though.

2024-03-06 10:25 UTC, Jeday commented on next.config.mjs
> +  publicRuntimeConfig: {
So are other envs, are they not available on backend? Why this one is special?

2024-03-06 10:26 UTC, Jeday commented on providers/index.tsx
>      <UserConfigProvider>
Inside provider we can split core functionality via hooks.

2024-03-06 10:33 UTC, Jeday commented on next.config.mjs
> +const basePath = process.env.BASE_PATH ?? '';
What is the consequence of that? 
Initially I would love all transformations, castings and fallbacks to happen in config not in next.config or in place of usage. Later we will add validations, that will error out on missing,invalid, misaligned(e.g default chain not in supported chains) envs, that will cause client runtime errors(build errors are not possible right now due to infra) so that we can detect env errors during QA effectively.

2024-03-07 11:17 UTC, solidovic commented on next.config.mjs
> +  publicRuntimeConfig: {
If we will deploy a Next.js application under a sub-path of a domain we should know it on client and backend.
https://nextjs.org/docs/pages/api-reference/next-config-js/basePath.

This implementation allows to store `basePath` in one place (.env file).

2024-03-07 12:30 UTC, solidovic commented on config/csp/index.ts
> +const reportOnly = secretConfig.cspReportOnly == 'true';
done

2024-03-14 04:33 UTC, Jeday approved these changes

2024-03-14 04:33 UTC, Jeday commented on config/get-preconfig.ts
> +// `getPreConfig()` needs for external internal in 'config/groups/*'
Not sure what this comment means. Let's rephrase.

2024-03-14 04:33 UTC, Jeday commented on config/get-preconfig.ts
> +// Not use `getPreConfig()` outside of 'config/groups/*'
Do not use

2024-03-14 04:35 UTC, Jeday commented on next.config.mjs
> +const basePath = process.env.BASE_PATH ?? '';
Yes. Let's do all other casting and validation in "config/get-preconfig.ts"

2024-03-14 11:37 UTC, Jeday approved these changes

2024-03-18 06:44 UTC, Jeday approved these changes

2024-03-18 06:44 UTC, Jeday commented on shared/hooks/use-mainnet-static-rpc-provider.ts
> +// TODO
Remove or clarify TODO

2024-03-18 07:13 UTC, Jeday approved these changes

2024-03-19 11:48 UTC, DiRaiks commented on utilsApi/getSmaStethApr.ts
> +    : 'https://eth-api.lido.fi';
Lets remove the hardcode fallback

2024-03-19 12:46 UTC, solidovic commented on utilsApi/getSmaStethApr.ts
> +    : 'https://eth-api.lido.fi';
This code from develop: https://github.com/lidofinance/ethereum-staking-widget/blob/develop/utilsApi/getSmaStethApr.ts#L57 and have TODO (**remove after deploy env variables**).

Are you sure to remove this hardcode?

2024-03-19 12:55 UTC, DiRaiks commented on utilsApi/getSmaStethApr.ts
> +    : 'https://eth-api.lido.fi';
yep. Env already added to infra

2024-03-19 13:11 UTC, solidovic commented on utilsApi/getSmaStethApr.ts
> +    : 'https://eth-api.lido.fi';
ok

2024-03-19 13:28 UTC, DiRaiks approved these changes

2024-03-19 13:29 UTC, Jeday approved these changes

2024-03-19 13:56 UTC, manneredboor submitted a review, later dismissed

2024-03-19 14:27 UTC, alx-khramov commented on config/get-secret-config.ts
> +// 'getSecretConfig()' needs for backend side.
```suggestion
// 'getSecretConfig()' is required for the backend side.
```

2024-03-19 14:27 UTC, alx-khramov commented on config/get-secret-config.ts
> +// Also you can note that 'getSecretConfig' is just proxy for 'serverRuntimeConfig'
```suggestion
// Also, you can note that 'getSecretConfig' is just a proxy for 'serverRuntimeConfig'
```

2024-03-19 14:27 UTC, alx-khramov commented on global.d.ts
> +      // cspReportOnly: boolean;
remove?

2024-03-20 06:20 UTC, solidovic commented on config/get-preconfig.ts
> +// `getPreConfig()` needs for internal in 'config/groups/*'
internal using.

fixed in code

2024-03-20 06:21 UTC, solidovic commented on config/rpc/index.ts
> +// '''
added comment

2024-03-20 10:04 UTC, Jeday approved these changes

2024-03-20 10:35 UTC, alx-khramov submitted a review, later dismissed
👍🏻

2024-03-20 11:23 UTC, alx-khramov submitted a review, later dismissed

2024-03-20 11:48 UTC, Jeday submitted a review, later dismissed

2024-03-20 12:55 UTC, DiRaiks submitted a review, later dismissed

2024-04-01 17:25 UTC, DiRaiks approved these changes

2024-04-08 08:19 UTC, merged