feat: dex will not be hidden if an error occured
lidofinance/ethereum-staking-widget pull request #251
Opened 2024-02-27 09:57 UTC by manneredboor

### Description

Showing '-' instead of removing withdrawal aggregator if an error occured

### Checklist:

- [x] Checked the changes locally.

2024-02-27 10:13 UTC, Jeday requested changes

2024-02-27 10:13 UTC, Jeday commented on features/withdrawals/request/form/options/dex-options.tsx
> +      {!initialLoading && data?.length === 0 && (
When `data?.length === 0` will be true? If integration array is empty? Maybe we should cover this before swr and  initialLoading?

2024-02-27 13:12 UTC, manneredboor commented on features/withdrawals/request/form/options/dex-options.tsx
> +      {!initialLoading && data?.length === 0 && (
Thank you for noticing, it is rudimentary now, I will remove it

2024-02-28 12:30 UTC, Jeday approved these changes

2024-03-04 07:16 UTC, DiRaiks approved these changes

2024-03-07 08:36 UTC, merged