feat: remove `*.lido.fi` hardcode domains
lidofinance/ethereum-staking-widget pull request #329
Opened 2024-05-06 18:14 UTC by solidovic

### Description

Removed all hardcode domains of `*.lido.fi`.
Use env vars instead of.

### Testing notes

Check:
- lido logo (in header)
- meta preview img in ipfs version
- links in banner 'Whitelist mode is on'
- rpc block in ipfs version
- FAQ 'What is Lido staking APR for Ethereum?'
- Link in text 'Represents how much ether you can stake at this moment. You cannot stake over the global staking limit. The....'
- Goerli sunset banner
- Link add NFT GUIDE
- PENALTIES INFO LINK
- FAQ How can I get steth
- FAQ How can I unstake steth
- FAQ How can I use steth
- FAQ Lido Eth apr
- FAQ How can I get wsteth
- FAQ How can I use wsteth
- L2 banner
- ECOSYSTEM LINK in modal_pool_banners
- footet

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-05-07 08:59 UTC, Jeday requested changes

2024-05-07 08:59 UTC, Jeday commented on .env.example
> +RESEARCH_ORIGIN=https://research.lido.fi
Set those envs with right consts in ipfs jobs yamls

2024-05-07 08:59 UTC, Jeday commented on pages/_document.tsx
> +    return `${config.selfOrigin}/lido-preview.png`;
We cannot know IPFS domain beforehand. It's okay to point to stake.lido.fi here

2024-05-13 07:14 UTC, solidovic commented on .env.example
> +RESEARCH_ORIGIN=https://research.lido.fi
done

2024-05-13 07:15 UTC, solidovic commented on pages/_document.tsx
> +    return `${config.selfOrigin}/lido-preview.png`;
done

2024-05-13 10:18 UTC, manneredboor approved these changes

2024-05-22 06:13 UTC, Jeday approved these changes

2024-05-23 08:56 UTC, DiRaiks submitted a review, later dismissed

2024-05-23 08:58 UTC, Jeday submitted a review, later dismissed

2024-05-23 09:50 UTC, alx-khramov submitted a review, later dismissed

2024-05-24 11:34 UTC, Jeday requested changes

2024-05-24 11:34 UTC, Jeday commented on features/stake/stake.tsx
> +        <LidoStats />
Why move into nossr wrapper? This content is static.

2024-05-24 11:34 UTC, Jeday commented on shared/components/layout/layout.tsx
> +      <NoSSRWrapper>
Why nossr footer?

2024-06-04 06:24 UTC, solidovic commented on shared/components/layout/layout.tsx
> +      <NoSSRWrapper>
revert

2024-06-04 06:24 UTC, solidovic commented on features/stake/stake.tsx
> +        <LidoStats />
revert

2024-06-07 07:15 UTC, Jeday approved these changes

2024-06-07 07:43 UTC, Jeday approved these changes

2024-06-07 12:50 UTC, jake4take approved these changes

2024-06-07 13:07 UTC, mvaleev approved these changes

2024-06-07 13:09 UTC, merged