[Feature] add error toast for rpc and validation errors
lidofinance/ethereum-staking-widget pull request #347
Opened 2024-06-07 11:05 UTC by Jeday

### Description

<img width="640" alt="image" src="https://github.com/lidofinance/ethereum-staking-widget/assets/3705803/907a8a92-8026-44e8-b9c6-aad391fd98c9">

### Demo

### Code review notes

### Testing notes
Block rpc to reproduce

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-06-13 10:23 UTC, DiRaiks approved these changes

2024-06-13 10:24 UTC, DiRaiks requested changes
I suggest moving the toast to the lower left corner so that it does not overlap the header interface.

2024-06-14 07:23 UTC, DiRaiks commented on shared/hook-form/validation/validation-error.ts
> +    position: 'bottom-right',
I meant the left corner and not the right

2024-06-14 07:27 UTC, Jeday commented on shared/hook-form/validation/validation-error.ts
> +    position: 'bottom-right',
fxied

2024-06-14 07:53 UTC, DiRaiks approved these changes

2024-06-19 11:37 UTC, jake4take approved these changes

2024-06-19 11:37 UTC, merged