feat: l2 fallback banner
lidofinance/ethereum-staking-widget pull request #371
Opened 2024-06-24 16:28 UTC by solidovic

### Description

Refactor the wallet-fallback unsupported chain block

Add L2-fallback block

### Demo

TOD

### Testing notes

TODO

### Checklist:

- [ ] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-07-05 12:46 UTC, alx-khramov requested changes
I feel like we should not use `useWeb3` and legacy "unsupported chain" logic in this task. I left more detailed comment in the team chat.

2024-07-05 12:46 UTC, alx-khramov commented on consts/chains.ts
> +  Arbitrum = 42161,
Forgot to remove these comments?

2024-07-05 12:46 UTC, alx-khramov commented on features/rewards/features/top-card/top-card.tsx
> +import { useWeb3 } from 'reef-knot/web3-react';
I think we should actually stop using this `useWeb3` wrapper. It was useful when some wallet connections worked via `web3-react`, but now we can use wagmi directly.

2024-07-05 12:46 UTC, alx-khramov commented on features/stake/stake-form/wallet/wallet.tsx
> +  const _chainId = accountChainId || chainIdWithoutAccount;
looks like you can use `chainId` instead of `_chainId` here

2024-07-05 12:46 UTC, alx-khramov commented on shared/hooks/use-chain-id-without-account.ts
> +        const chainIdHex = await window?.ethereum?.request({
I feel like that it is not good idea to call `window.ethereum` from here. Especially considering https://github.com/lidofinance/reef-knot/pull/140, where wallet providers will be stored and used in another way.
I think you need to get current connector and then something like `connector.getProvider()`, see this: https://github.com/wevm/wagmi/blob/main/packages/core/src/connectors/injected.ts#L309

2024-07-05 12:46 UTC, alx-khramov commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +  // [L2_CHAINS.Arbitrum_One]: ArbitrumLogo,
to remove?

2024-07-05 12:46 UTC, alx-khramov commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +        // onClick={() => console.log('Track Matomo!')}
don't forget to remove

2024-07-05 12:46 UTC, alx-khramov commented on shared/wallet/l2-fallback/styles.tsx
> +    // TODO
what?

2024-07-09 20:59 UTC, solidovic commented on shared/wallet/l2-fallback/styles.tsx
> +    // TODO
we are waiting design updates

2024-07-09 21:00 UTC, solidovic commented on features/stake/stake-form/wallet/wallet.tsx
> +  const _chainId = accountChainId || chainIdWithoutAccount;
outdated

2024-07-09 21:01 UTC, solidovic commented on features/rewards/features/top-card/top-card.tsx
> +import { useWeb3 } from 'reef-knot/web3-react';
outdated

2024-07-09 21:01 UTC, solidovic commented on features/rewards/features/top-card/top-card.tsx
> +      {address ? active ? <Wallet /> : <Fallback /> : <ConnectWallet />}
outdated

2024-07-09 21:08 UTC, solidovic commented on consts/chains.ts
> +  Arbitrum = 42161,
done

2024-07-09 21:09 UTC, solidovic commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +  // [L2_CHAINS.Arbitrum_One]: ArbitrumLogo,
done

2024-07-09 21:09 UTC, solidovic commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +        // onClick={() => console.log('Track Matomo!')}
done

2024-07-09 22:12 UTC, solidovic commented on shared/hooks/use-chain-id-without-account.ts
> +        const chainIdHex = await window?.ethereum?.request({
removed useChainIdWithoutAccount

2024-07-10 09:28 UTC, alx-khramov approved these changes

2024-07-12 11:17 UTC, DiRaiks commented on features/rewards/features/top-card/wallet.tsx
> +const WalletStyle = styled(WalletCardStyle)`
lets move to styles file

2024-07-12 11:20 UTC, DiRaiks commented on shared/hook-form/controls/token-select-hook-form.tsx
> +    // The '!important' is important here!
Add reason for important flag

2024-07-12 11:29 UTC, DiRaiks commented on shared/hooks/use-dapp-statuses.ts
> +      Object.values(L2_CHAINS).indexOf(chainId as unknown as L2_CHAINS) > -1
```!!L2_CHAINS[chainId as unknown as L2_CHAINS]```

2024-07-12 11:29 UTC, DiRaiks commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +    return Object.keys(L2_CHAINS)[
```L2_CHAINS[chainId as unknown as L2_CHAINS]```

2024-07-12 11:33 UTC, DiRaiks commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +      {getL2Logo(chainId as unknown as L2_CHAINS)}
```getL2Logo(chainId as L2_CHAINS)```

2024-07-12 11:34 UTC, DiRaiks commented on shared/wallet/unsupported-chain-button/unsupported-chain-button.tsx
> +export const ButtonStyle = styled((props) => <Button {...props} />)`
lets move to styles file

2024-07-12 12:52 UTC, solidovic commented on shared/hooks/use-dapp-statuses.ts
> +      Object.values(L2_CHAINS).indexOf(chainId as unknown as L2_CHAINS) > -1
done

2024-07-12 13:09 UTC, solidovic commented on shared/hook-form/controls/token-select-hook-form.tsx
> +    // The '!important' is important here!
added

2024-07-12 13:10 UTC, solidovic commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +      {getL2Logo(chainId as unknown as L2_CHAINS)}
done

2024-07-12 13:17 UTC, solidovic commented on shared/wallet/unsupported-chain-button/unsupported-chain-button.tsx
> +export const ButtonStyle = styled((props) => <Button {...props} />)`
done

2024-07-12 13:17 UTC, solidovic commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +    return Object.keys(L2_CHAINS)[
done

2024-07-12 13:17 UTC, solidovic commented on features/rewards/features/top-card/wallet.tsx
> +const WalletStyle = styled(WalletCardStyle)`
done

2024-07-15 08:14 UTC, DiRaiks commented on shared/hook-form/controls/token-select-hook-form.tsx
> +export const SelectIconStyle = styled((props) => <SelectIcon {...props} />)`
To styles.ts

2024-07-15 08:15 UTC, DiRaiks commented on shared/wallet/button/button.tsx
> +      style={
Move prop to styled component in styles.ts

2024-07-15 08:16 UTC, DiRaiks commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +        href={'https://lido.fi/lido-on-l2'}
I think here should used env for domain

2024-07-15 08:17 UTC, DiRaiks commented on shared/wallet/l2-fallback/styles.tsx
> +    // TODO
Still waiting for the design?

2024-07-15 08:46 UTC, solidovic commented on shared/wallet/l2-fallback/styles.tsx
> +    // TODO
we got a updates today

2024-07-15 09:02 UTC, solidovic commented on shared/wallet/l2-fallback/styles.tsx
> +    // TODO
done

2024-07-15 12:00 UTC, solidovic commented on shared/wallet/l2-fallback/l2-fallback.tsx
> +        href={'https://lido.fi/lido-on-l2'}
done

2024-07-15 12:00 UTC, solidovic commented on shared/wallet/button/button.tsx
> +      style={
done

2024-07-15 12:00 UTC, solidovic commented on shared/hook-form/controls/token-select-hook-form.tsx
> +export const SelectIconStyle = styled((props) => <SelectIcon {...props} />)`
done

2024-07-15 12:00 UTC, solidovic commented on features/rewards/features/top-card/connect-wallet.tsx
> +const ConnectWalletStyle = styled(WalletCardStyle)`
done

2024-07-25 14:06 UTC, DiRaiks approved these changes

2024-07-25 14:08 UTC, merged