feat: wagmi version updated
lidofinance/ethereum-staking-widget pull request #376
Opened 2024-07-01 09:57 UTC by manneredboor

### Description

Wagmi version updated

### Checklist:

- [x] Checked the changes locally.

2024-07-02 11:10 UTC, Jeday approved these changes

2024-07-02 11:10 UTC, Jeday commented on providers/sdk-legacy.tsx
> +  const providerRpc = getStaticRpcBatchProvider(
Why useMemo is removed?

2024-07-02 11:10 UTC, Jeday requested changes

2024-07-02 11:10 UTC, Jeday commented on providers/sdk-legacy.tsx
> +  const providerMainnetRpc = getStaticRpcBatchProvider(
useMemo?

2024-07-02 11:16 UTC, manneredboor commented on providers/sdk-legacy.tsx
> +  const providerRpc = getStaticRpcBatchProvider(
The `getStaticRpcBatchProvider` function has a memo inside itself already

2024-07-02 11:20 UTC, Jeday approved these changes

2024-07-02 12:45 UTC, solidovic approved these changes

2024-07-05 09:00 UTC, DiRaiks approved these changes

2024-07-05 09:11 UTC, merged

2024-07-05 11:43 UTC, alx-khramov reviewed
LGTM ✅