[Feature] new aggregator Jumper for withdrawals widget
lidofinance/ethereum-staking-widget pull request #381
Opened 2024-07-02 13:13 UTC by Jeday

### Description

- added new dex Jumper
- updated styles to support >3 dexes
- did not enable it config yet

### Demo

<img width="550" alt="image" src="https://github.com/lidofinance/ethereum-staking-widget/assets/3705803/1fbfae81-b906-4e5b-83f3-88e764e7076d">

### Code review notes

### Testing notes

Can be checked with `mock-qa-helpers-enabled-withdrawal-dexes`=`['one-inch', 'paraswap', 'bebop','jumper']`
After #344 is merged, if this branch is updated, can be tested by overriding IPFS.json

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-07-03 14:12 UTC, DiRaiks commented on features/withdrawals/request/form/options/styles.tsx
> +  <svg
Might it make sense to move the svg to the icons folder?

2024-07-04 03:40 UTC, Jeday commented on features/withdrawals/request/form/options/styles.tsx
> +  <svg
I thought I might need to dynamic render this svg, but forgot to move to icons

2024-07-04 04:26 UTC, Jeday commented on features/withdrawals/request/form/options/styles.tsx
> +  <svg
fixed

2024-07-04 10:59 UTC, DiRaiks requested changes

2024-07-04 10:59 UTC, DiRaiks commented on features/withdrawals/request/form/options/dex-options/styles.ts
> +  $showMore: boolean;
It is not used here

2024-07-04 10:59 UTC, DiRaiks commented on features/withdrawals/request/form/options/dex-options/dex-options.tsx
> +        $showMore={showMore}
not nessary props

2024-07-04 11:10 UTC, DiRaiks approved these changes
lgtm

2024-07-10 12:51 UTC, merged