refactor: remove input form from reward page
lidofinance/ethereum-staking-widget pull request #407
Opened 2024-07-19 11:24 UTC by solidovic

### Description

### Demo

### Code review notes

### Testing notes

### Checklist:

- [ ] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-07-22 09:56 UTC, manneredboor commented on features/rewards/features/top-card/wallet.tsx
> -import { AddressInput } from 'features/rewards/components/addressInput';
The `features/rewards/components/addressInput` directory also could be removed

2024-07-22 10:00 UTC, manneredboor commented on features/rewards/features/top-card/wallet.tsx
>            <InputDescription>{INPUT_DESC_TEXT}</InputDescription>
The `InputDescription` component naming does not reflect actual usage since there is no longer input on the page, maybe we can make up a different naming for it

2024-07-31 11:17 UTC, solidovic commented on features/rewards/features/top-card/wallet.tsx
>            <InputDescription>{INPUT_DESC_TEXT}</InputDescription>
done

2024-07-31 11:20 UTC, solidovic commented on features/rewards/features/top-card/wallet.tsx
> -import { AddressInput } from 'features/rewards/components/addressInput';
done

2024-08-06 05:46 UTC, Jeday requested changes

2024-08-06 05:46 UTC, Jeday commented on providers/rewardsHistory.tsx
let's add qa helper to allow address from local storage.

2024-08-06 11:08 UTC, Jeday submitted a review, later dismissed

2024-08-07 11:49 UTC, Jeday approved these changes

2024-08-07 12:24 UTC, merged