feat: add env vars logging and push them to prom.
lidofinance/ethereum-staking-widget pull request #448
Opened 2024-08-26 14:51 UTC by solidovic

### Description

- feat: add ENV logging
- feat: push open ENV vars to prom

### Code review notes

Check secret env vars

### Testing notes

nothing

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-08-27 05:42 UTC, Jeday requested changes

2024-08-27 05:42 UTC, Jeday commented on utilsApi/metrics/metrics.ts
> +    collectStartupMetrics(this.registry);
Not sure why we need this method. We can call this in constructor same as  collectDefaultMetrics

2024-08-27 09:06 UTC, Jeday submitted a review, later dismissed

2024-08-27 09:19 UTC, DiRaiks commented on utilsApi/metrics/startup-metrics.ts
> +const labelPairs = [
Wdyt about like this
```
import { openKeys } from 'scripts/log-environment-variables.mjs';

const labelPairs = openKeys.map((key) => {
  return { name: key, value: process.env[key] };
});
```

2024-08-28 11:57 UTC, Jeday commented on scripts/startup-check-rpc.mjs
> +    console.debug('[startupCheckRPC] OK!');
for ok, not debug but info, so we can see it in default level logs

2024-09-02 07:31 UTC, Jeday requested changes

2024-09-02 07:31 UTC, Jeday commented on scripts/startup-checks/rpc.mjs
> +import { ethers } from 'ethers';
Because we are slowly migrating away from ethers, let's do new code with viem instead. Difference is minimal
```ts
import { createClient, http } from 'viem'
 
const client = createClient({ 
  transport: http('RPC_URL',{options like retry})
})
 
```

2024-09-02 09:53 UTC, solidovic commented on scripts/startup-checks/rpc.mjs
> +import { ethers } from 'ethers';
done

2024-09-02 09:53 UTC, solidovic commented on scripts/startup-check-rpc.mjs
> +    console.debug('[startupCheckRPC] OK!');
fixed

2024-09-02 09:53 UTC, solidovic commented on utilsApi/metrics/startup-metrics.ts
> +const labelPairs = [
done

2024-09-02 09:58 UTC, Jeday submitted a review, later dismissed

2024-09-02 11:30 UTC, DiRaiks submitted a review, later dismissed

2024-09-02 15:51 UTC, Jeday approved these changes

2024-09-02 16:15 UTC, DiRaiks approved these changes

2024-09-03 06:10 UTC, merged