Feature/si 1606 steth on optimism wrapunwrap
lidofinance/ethereum-staking-widget pull request #484
Opened 2024-10-01 11:58 UTC by solidovic

### Description

### Demo

### Code review notes

### Testing notes

### Checklist:

- [ ] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-10-04 06:24 UTC, Jeday requested changes

2024-10-04 06:24 UTC, Jeday commented on features/wsteth/wrap/wrap-form-controls/token-select-wrap.tsx
> +      options={options}
There is no options in design

2024-10-04 06:24 UTC, Jeday commented on utils/get-etherscan-tx-link.ts
> +  if (chainId === CHAINS.OptimismSepolia) {
You can get explorer url from viem chains object https://viem.sh/docs/chains/introduction

2024-10-04 06:24 UTC, Jeday commented on shared/hooks/use-dapp-status.ts
> +  const isAccountActiveOnL1 = useMemo(() => {
All those memos can be unified into one via object.

2024-10-04 06:24 UTC, Jeday commented on shared/components/layout/header/components/chain-switcher/styles.tsx
> +export const SelectIconStyled = styled(SelectIcon)`
Height does not match design and rest of the header

2024-10-04 06:24 UTC, Jeday commented on providers/lido-sdk.tsx
>        rpcUrls: !publicClient && fallbackRpcUrl ? [fallbackRpcUrl] : undefined,
This might not be actual anymore with usePublicClient

2024-10-04 06:24 UTC, Jeday commented on providers/lido-sdk.tsx
> +  lidoSDKCore: LidoSDKCore;
let's use shorter names like in LidoSDK fields

2024-10-04 06:24 UTC, Jeday commented on providers/index.tsx
> +      <DappChainProvider>
Would it make sense to have it under web3provider and derive state from it

2024-10-04 08:17 UTC, solidovic commented on utils/get-etherscan-tx-link.ts
> +  if (chainId === CHAINS.OptimismSepolia) {
explorer

2024-10-04 08:19 UTC, solidovic commented on shared/hooks/use-dapp-status.ts
> +  const isAccountActiveOnL1 = useMemo(() => {
one big use memo

2024-10-04 08:20 UTC, solidovic commented on providers/lido-sdk.tsx
>        rpcUrls: !publicClient && fallbackRpcUrl ? [fallbackRpcUrl] : undefined,
check removing rpcUrls

2024-10-04 08:58 UTC, solidovic commented on IPFS.json
> +  "10": {
done

2024-10-04 09:08 UTC, solidovic commented on shared/hooks/use-dapp-status.ts
> +  const isAccountActiveOnL1 = useMemo(() => {
done

2024-10-04 09:18 UTC, solidovic commented on shared/components/layout/header/components/chain-switcher/styles.tsx
> +export const SelectIconStyled = styled(SelectIcon)`
fixed

2024-10-04 09:51 UTC, solidovic commented on providers/lido-sdk.tsx
> +  lidoSDKCore: LidoSDKCore;
refactored

2024-10-04 13:38 UTC, solidovic commented on providers/index.tsx
> +      <DappChainProvider>
Web3Provider implicitly depends on DappChainProvider

2024-10-04 13:45 UTC, solidovic commented on utils/get-etherscan-tx-link.ts
> +  if (chainId === CHAINS.OptimismSepolia) {
let's do it later

2024-10-04 14:06 UTC, Jeday submitted a review, later dismissed

2024-10-07 06:22 UTC, Jeday commented on shared/hooks/use-wstETH-by-stETH-on-l2.ts
> +    wsteth ? [wsteth.toBigInt()] : null,
Do this not fetch on null key? Needs rechek or comment.

2024-10-07 06:22 UTC, Jeday commented on shared/hooks/use-stETH-by-wstETH-on-l2.ts
> +    wsteth ? [wsteth.toBigInt()] : null,
same comment in useWstETHByStETHOnL2

2024-10-07 06:22 UTC, Jeday commented on shared/components/data-table-row-steth-by-wsteth/data-table-row-steth-by-wsteth.tsx
> +  const { data: dataOnL1, initialLoading: initialLoadingOnL1 } =
If typing is the same you could do 
```
const swrL2 = ...
const swrL1 = ...
const { data, initialLoading } = isL2 ? swrL2 : swrL1
```

2024-10-07 06:22 UTC, Jeday commented on features/wsteth/wrap/wrap-form/wrap-stats.tsx
> +  const {
Same comment about shorting swr code

2024-10-07 06:32 UTC, Jeday commented on features/wsteth/unwrap/hooks/use-unwrap-tx-on-l2-approve.ts
> +  const refetchAllowance = useCallback(() => {
@solidovic  up

2024-10-07 07:20 UTC, solidovic commented on shared/hooks/use-wstETH-by-stETH-on-l2.ts
> +    wsteth ? [wsteth.toBigInt()] : null,
added comment 

' // if key is null, SWR will not fetch any data.' 

https://swr.vercel.app/docs/conditional-fetching#conditional

2024-10-07 07:20 UTC, solidovic commented on shared/hooks/use-stETH-by-wstETH-on-l2.ts
> +    wsteth ? [wsteth.toBigInt()] : null,
added comment 

' // if key is null, SWR will not fetch any data.' 

https://swr.vercel.app/docs/conditional-fetching#conditional

2024-10-07 07:36 UTC, solidovic commented on features/wsteth/wrap/wrap-form/wrap-stats.tsx
> +  const {
refactored

2024-10-07 07:36 UTC, solidovic commented on shared/components/data-table-row-steth-by-wsteth/data-table-row-steth-by-wsteth.tsx
> +  const { data: dataOnL1, initialLoading: initialLoadingOnL1 } =
refactored

2024-10-07 11:21 UTC, Jeday approved these changes

2024-10-07 12:52 UTC, Jeday approved these changes

2024-10-07 14:03 UTC, Jeday approved these changes

2024-10-08 06:22 UTC, Jeday approved these changes

2024-10-08 10:48 UTC, Jeday submitted a review, later dismissed

2024-10-08 17:37 UTC, Jeday approved these changes

2024-10-08 17:38 UTC, merged

2024-10-09 08:04 UTC, Jeday commented on shared/wallet/lido-multichain-fallback/lido-multichain-fallback.tsx
> +  const { chainId: chainIdWagmin } = useAccount();
sorry it as late

2024-10-09 08:05 UTC, Jeday commented on features/rewards/features/top-card/top-card.tsx
> +      )}
you are right, initialy we had different texts  here

2024-10-09 08:10 UTC, solidovic commented on features/rewards/features/top-card/top-card.tsx
> +      )}
specially made (for the 'isAccountActiveOnL2' case can be anther text). will fix it soon (not this iteration).