Fix/stats
lidofinance/ethereum-staking-widget pull request #513
Opened 2024-10-17 10:54 UTC by solidovic

### Description

- fix(unwrap stats): hide allowance (if he is not needed)
- fix(wq stats): hide stats for l2

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-10-17 12:13 UTC, Jeday commented on features/withdrawals/request/form/transaction-info.tsx
> +        {isWalletConnected && !isDappActiveAndNetworksMatched ? (
Why is this condition different from one in claim/transactin-info?

2024-10-17 12:51 UTC, DiRaiks requested changes
I suggest changing the approach to writing code. The current number of flags and completely different approaches to their use leads to a lack of understanding of what is happening in the code and why. In the future this will become a magic box with a support problem. I cannot agree to merge in the form that it is now

2024-10-17 15:02 UTC, Jeday approved these changes

2024-10-17 15:04 UTC, Jeday commented
@DiRaiks completely agree, I addressed those issues in https://github.com/lidofinance/ethereum-staking-widget/pull/510. We might be able to incorporate #513 in #510 to fix situation.

2024-10-24 11:13 UTC, solidovic commented
resolved in https://github.com/lidofinance/ethereum-staking-widget/pull/510

2024-10-24 11:13 UTC, closed without merging