[WIP] refactor: l2 tech debt improvement
lidofinance/ethereum-staking-widget pull request #524
Opened 2024-10-28 08:23 UTC by solidovic

### Description

**if the ChainType not matched:**
- refactor: show the allowance
- refactor(wrap): show the 'stats'
- refactor(unwrap): show the 'stats'

### Demo

[TODO]

### Code review notes

See the 'chainTypeChainId' in the 'useDappChain'

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-10-29 11:54 UTC, Jeday requested changes

2024-10-29 11:54 UTC, Jeday commented on features/wsteth/unwrap/unwrap-form/unwrap-stats.tsx
> +  const chainIdForce = !isChainTypeMatched ? chainTypeChainId : undefined;
I think we should inforce `chainTypeChainId` is correct when `!isChainTypeMatched` so that this condintion would not be needed.

2024-10-29 11:54 UTC, Jeday commented on features/wsteth/wrap/hooks/use-wrap-tx-on-l1-approve.ts
> +        !isWalletConnected || isDappActiveOnL1 || !isChainTypeOnL2,
try only comndtion `!isChainTypeOnL2` I think this might work.

2024-10-29 11:54 UTC, Jeday commented on features/wsteth/wrap/wrap-form/wrap-stats.tsx
> +  const chainIdForce = !isChainTypeMatched ? chainTypeChainId : undefined;
Same for comment as `features/wsteth/unwrap/unwrap-form/unwrap-stats.tsx`

2024-10-29 11:54 UTC, Jeday commented on modules/web3/hooks/use-max-gas-price.ts
> +export const useMaxGasPrice = (chainIdForce?: number) => {
just `chainId` argument naming would already be correct, force is exhessive

2024-10-29 11:54 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +          isChainTypeOnL2: isConnected
isConnected check is not needed

2024-10-29 12:10 UTC, solidovic commented on modules/web3/web3-provider/dapp-chain.tsx
> +          isChainTypeOnL2: isConnected
without this flag if it was selected Optimism and after wallet was disconnect the isChainTypeOnL2 will be true

2024-10-29 12:48 UTC, solidovic commented on modules/web3/hooks/use-max-gas-price.ts
> +export const useMaxGasPrice = (chainIdForce?: number) => {
I named the variable this way because below we take "chainId" from "useDappStatus"

2024-10-29 12:55 UTC, solidovic commented on features/wsteth/unwrap/unwrap-form/unwrap-stats.tsx
> +  const chainIdForce = !isChainTypeMatched ? chainTypeChainId : undefined;
The "chainTypeChainId" is correct according to "chain switch".
Thanks for paid attention this code.
It seems we can just use the "chainTypeChainId"

2024-10-29 12:56 UTC, solidovic commented on features/wsteth/wrap/wrap-form/wrap-stats.tsx
> +  const chainIdForce = !isChainTypeMatched ? chainTypeChainId : undefined;
same answer as for `features/wsteth/unwrap/unwrap-form/unwrap-stats.tsx`

2024-10-29 13:25 UTC, solidovic commented on modules/web3/web3-provider/dapp-chain.tsx
> +          isChainTypeOnL2: isConnected
as an option. This check is equivalent for 'to reset on disconnect'

2024-10-30 07:25 UTC, Jeday requested changes

2024-10-30 07:25 UTC, Jeday commented on shared/components/allowance-data-table-row/allowance-data-table-row.tsx
> +          amount={BigNumber.from('0')}
Use `Zero` constant from ethers

2024-10-30 07:25 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +    if (isConnected && walletChainId) {
Redo simpler please

2024-10-30 07:25 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +const getChainIdByChainType = (
We can simplify this code(it won't be most optimized but its okay at this data size).
`return supportedChainIds.find(id=>getChainTypeByChainId(id)===chainType)`

2024-10-30 07:25 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +const getChainIdByChainType = (
Alternatively, do 
```ts 
const CHAINS= //get ETHEREUM_CHAINS or OPTIMISM_CHAINS based on chainType
return supportedChainIds.find(id=>CHAINS.has(id))
```

2024-10-30 07:25 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +const getChainIdByChainType = (
any will do

2024-10-30 07:54 UTC, Jeday approved these changes

2024-10-30 07:58 UTC, merged