[WIP] feat: chain toggle changes wallet chain
lidofinance/ethereum-staking-widget pull request #530
Opened 2024-10-30 09:20 UTC by solidovic

### Description

todo

### Code review notes

todo

### Testing notes

todo

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-11-01 04:17 UTC, Jeday requested changes

2024-11-01 04:17 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +      switchChain({ chainId: newChainId });
We need to check if cuurent connector has `switchChain` method and avoid calling this. Also error handlers that print warning to console if switchChain failed.

2024-11-01 04:17 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +      switchChain({ chainId: newChainId });
Also would love to experiment with async UX, where we on user selecting chain and if there is `switchChain` avaliable:
 - disable selector UI
 - try with timeout to swithChain
 - if successfull then commit changes with `setChainType`
 - if error toast user

2024-11-01 04:17 UTC, Jeday commented on modules/web3/web3-provider/dapp-chain.tsx
> +    (newChainType) => {
I am thinking we try something here:
 Instead of chainType on selector, we select chainId. So for tesntent we would have Holesky and OP sepolia namings. No changes to prod UX. Also would allow in dev to select any chain you have in supported. This would also simpligy this code as chainId->chainType mapping is very clear.
 ChainType still serves a purpose, as it allows us to get correct UI color and etc.

2024-11-06 08:13 UTC, solidovic commented
This is pending the integration of the new SDK

2025-01-20 06:50 UTC, solidovic commented
see: https://github.com/lidofinance/ethereum-staking-widget/pull/571

2025-01-20 06:50 UTC, closed without merging