[WIP] feat: future setup for support other l2
lidofinance/ethereum-staking-widget pull request #533
Opened 2024-10-31 11:10 UTC by solidovic

### Description

todo

### Code review notes

todo

### Testing notes

todo

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-11-01 04:31 UTC, Jeday requested changes

2024-11-01 04:31 UTC, Jeday commented on utils/etherscan.ts
> +      `https://etherscan1.io/${entity}/${hash}`;
WTF is this domain???

2024-11-01 04:31 UTC, Jeday commented on utils/etherscan.ts
> +      `https://etherscan1.io/${entity}/${hash}`;
Also let's just do invairaint here. We won't have non-wagmi chain.

2024-11-01 04:31 UTC, Jeday commented on features/wsteth/shared/wrap-faq/wrap-faq.tsx
> +      {React.createElement(faqComponent, { key: chainType })}
Just use UpperCase for it be jsx.

2024-11-01 04:31 UTC, Jeday commented on shared/components/tx-link-etherscan/tx-link-etherscan.tsx
> +  const { walletChainId } = useDappStatus();
Why use walletChainId? If we don't support chain we should not try to link correct explorer, just use chainId(it defaults to correct chain)

2024-11-01 13:04 UTC, solidovic commented on shared/components/tx-link-etherscan/tx-link-etherscan.tsx
> +  const { walletChainId } = useDappStatus();
<img width="389" alt="image" src="https://github.com/user-attachments/assets/e4b17424-9d59-4eec-9a3b-ea22bfe72d6e">
This component is used in TransactionModal, which is wrapped by SupportL1Chains, but not wrapped by SupportL2Chains.
This is currently the fastest solution

2024-11-01 13:16 UTC, solidovic commented on features/wsteth/shared/wrap-faq/wrap-faq.tsx
> +      {React.createElement(faqComponent, { key: chainType })}
A rudiment remained after coding

2024-11-06 07:49 UTC, Jeday submitted a review, later dismissed

2024-11-06 07:50 UTC, Jeday commented on utils/etherscan.ts
> +      `https://etherscan1.io/${entity}/${hash}`;
I freaked out because it's apparently a fishing domain.

2024-11-29 08:45 UTC, Jeday approved these changes

2024-12-03 08:55 UTC, merged