refactor: migrate to new SDK, to bigint, to viem, to react-query
lidofinance/ethereum-staking-widget pull request #543
Opened 2024-11-15 15:08 UTC by solidovic

### Description

1) Migrate from BigNumber to bigint.

2) Migrate from old SDK to the new SDK.

Operations:
- stake;
- wrap;
- unwrap;
- withdrawal
work through the new SDK.

Requests for:
- balances;
- limits (stake limits);
- and other on-chain data
are taken through the functionality of the new SDK.

3) Migrate from SWR to 'react-query'.

4) Removed the typechain package.
Now `*abi.ts` files are used (in some cases with too much interface description).

5) Migrate from `ethers` to `viem` and removed packages: `ethers`, `@ethersproject/*`.

6) APR fallback: if ETH-API is not available, then SDK is used.

7) Unused code has been removed.

8) There was a reduction in the number of lines of code.

9) Override a babel config

### Code review notes

...

### Testing notes

The whole widget

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-11-22 12:04 UTC, Jeday requested changes

2024-11-22 12:04 UTC, Jeday commented on features/withdrawals/hooks/useNftDataByTxHash.ts
> +            .read.tokenURI([Number(e.args.requestId)]);
NO!!!!!
 withdraw.contract.getContractWithdrawalQueue() returns promise with contract instance and must be awaited
 Please await instance of wq contract above

2024-11-22 12:04 UTC, Jeday commented on features/withdrawals/request/form/controls/token-amount-input-request.tsx
> +        balanceDiff && balanceDiff !== BigInt(0) ? (
just balanceDiff, please read how native js bigint behaves

2024-11-22 12:04 UTC, Jeday commented on features/withdrawals/request/form/controls/token-select-request.tsx
> +import { TOKENS_TO_WRAP } from '../../../../wsteth/shared/types';
I saw withdrable tokens enum. Change to it.

2024-11-22 12:08 UTC, Jeday commented on utils/getNFTUrl.ts
> +  contractAddress?: Address | string | null,
if we use only new sdk, by ambious type

2024-11-22 12:21 UTC, Jeday commented on package.json
>      "@tanstack/react-query": "^5.51.21",
up wagmi/viem to latests versions

2024-11-22 12:24 UTC, Jeday commented on modules/web3/web3-provider/web3-provider.tsx
>      <WagmiProvider config={wagmiConfig} reconnectOnMount={false}>
Why QueryClientProvider is removed?
https://wagmi.sh/react/getting-started#setup-tanstack-query
it's in the docs

2024-11-22 12:27 UTC, Jeday commented on modules/web3/web3-provider/web3-provider.tsx
> +      chains: supportedChains.includes(wagmiChains.mainnet)
Not sure if I like this. Can you estimate the usage of all mainnet-only calls? Maybe we can create a separate wagmi config object for those, it will be read only, no wallet. Config can be passed directly to wagmi hooks.

2024-11-22 12:27 UTC, Jeday commented on modules/web3/web3-provider/web3-provider.tsx
> +      chains: supportedChains.includes(wagmiChains.mainnet)
This way we can remove `add mainnet` hacks from code.

2024-11-22 12:28 UTC, Jeday commented on modules/web3/web3-provider/lido-sdk.tsx
> +      shares,
we need shares?

2024-11-22 12:30 UTC, Jeday commented on modules/web3/hooks/use-wsteth-contract-address.ts
> +    initialLoading: isLoading && !data && !error,
just return queryResult

2024-11-22 12:30 UTC, Jeday commented on modules/web3/hooks/use-wstETH-by-stETH.ts
> +  const { data, error, isLoading, isFetching, refetch } = useQuery({
just retrun here

2024-11-22 12:31 UTC, Jeday commented on modules/web3/hooks/use-wstETH-by-stETH.ts
> +        : shares.convertToShares(steth);
wrap.convertStethToWsteth

2024-11-22 12:31 UTC, Jeday commented on modules/web3/hooks/use-steth-contract-address.ts
> +  const { data, error, isLoading, isFetching } = useQuery({
return here

2024-11-22 12:31 UTC, Jeday commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +        : shares.convertToSteth(wsteth);
wrap.convertWstethToSteth

2024-11-22 12:32 UTC, Jeday commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +  const { data, error, isLoading, isFetching, refetch } = useQuery({
return here

2024-11-22 12:33 UTC, Jeday commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +      if (wsteth == null) return undefined;
bad, never return undefined from queryFn this will pollute cache. You can put invariant here

2024-11-22 12:35 UTC, Jeday commented on modules/web3/consts/units.ts
> +export const MAX_UINT_256 = BigInt(
viem maxUint256

2024-11-22 12:36 UTC, Jeday commented on modules/web3/consts/tx.ts
> +export const ADDRESS_ZERO = '0x0000000000000000000000000000000000000000';
viem   zeroAddress  and change all usages to viem const

2024-11-22 12:38 UTC, Jeday commented on features/wsteth/wrap/wrap-form-controls/token-amount-input-wrap.tsx
> +      isLocked={!!isApprovalNeededBeforeWrap}
do boolean conv where  isApprovalNeededBeforeWrap is assigned

2024-11-22 12:38 UTC, Jeday commented on features/wsteth/wrap/wrap-form-controls/submit-button-wrap.tsx
> +      isLocked={!!isLocked}
do bool conv where value is assigned

2024-11-22 12:48 UTC, Jeday commented on abi/lido-locator.ts
@lidofinance/lido-ethereum-sdk 4.1.0-alpha.3

2024-11-23 10:28 UTC, solidovic commented on abi/lido-locator.ts
done

2024-11-23 10:28 UTC, solidovic commented on config/external-config/types.ts
> +import { UseQueryResult } from '@tanstack/react-query';
done

2024-11-23 10:58 UTC, solidovic commented on features/ipfs/security-status-banner/use-remote-version.ts
>      get initialLoading() {
done

2024-11-23 11:04 UTC, solidovic commented on features/rewards/components/rewardsListContent/RewardsListContent.tsx
> +  const hasSteth = stethBalance !== undefined && stethBalance > ZERO;
done

2024-11-23 11:05 UTC, solidovic commented on features/rewards/hooks/use-rewards-balance-data.ts
> +              // not safe
done

2024-11-23 11:06 UTC, solidovic commented on features/stake/stake-form/stake-form-context/stake-form-context.tsx
> +    refetch: mutateStakeLimit,
done

2024-11-23 11:18 UTC, solidovic commented on features/stake/stake-form/use-stake.ts
> +          ? await getAddress(referral, stake.core.rpcProvider)
done

2024-11-23 11:18 UTC, solidovic commented on features/stake/stake-form/stake-form-context/validation.ts
> +      gasCost: gasCost,
done

2024-11-23 11:21 UTC, solidovic commented on features/withdrawals/request/form/controls/token-amount-input-request.tsx
> +        balanceDiff && balanceDiff !== BigInt(0) ? (
done

2024-11-23 11:23 UTC, solidovic commented on features/withdrawals/request/form/controls/token-select-request.tsx
> +import { TOKENS_TO_WRAP } from '../../../../wsteth/shared/types';
fixed

2024-11-23 11:31 UTC, solidovic commented on modules/web3/consts/units.ts
> +export const MAX_UINT_256 = BigInt(
done

2024-11-23 11:39 UTC, solidovic commented on modules/web3/web3-provider/lido-sdk.tsx
> +      shares,
we use:
- shares.convertToSteth(wsteth)
- shares.convertToShares(steth)

2024-11-23 11:41 UTC, solidovic commented on features/withdrawals/claim/form/submit-button.tsx
> +    ethToClaim <= ZERO ? null : (
done

2024-11-23 11:42 UTC, solidovic commented on features/withdrawals/hooks/contract/use-withdrawal-approve.ts
> +    amount > BigInt('0')
done

2024-11-23 11:51 UTC, solidovic commented on features/withdrawals/hooks/contract/useTotalSupply.ts
> +import { useQuery, UseQueryResult } from '@tanstack/react-query';
done

2024-11-23 12:05 UTC, solidovic commented on features/withdrawals/request/form/controls/token-select-request.tsx
> +import { TOKENS_TO_WRAP } from '../../../../wsteth/shared/types';
done

2024-11-23 12:06 UTC, solidovic commented on features/withdrawals/request/form/controls/token-amount-input-request.tsx
> +        balanceDiff && balanceDiff !== BigInt(0) ? (
done

2024-11-23 12:20 UTC, solidovic commented on features/stake/stake-form/hooks/use-tx-modal-stages-stake.tsx
> +  pending: (amount: bigint, txHash?: Address) =>
done

2024-11-24 05:20 UTC, solidovic commented on utils/getNFTUrl.ts
> +  contractAddress?: Address | string | null,
done

2024-11-24 05:23 UTC, solidovic commented on modules/web3/hooks/use-wsteth-contract-address.ts
> +    initialLoading: isLoading && !data && !error,
done

2024-11-24 05:32 UTC, solidovic commented on modules/web3/hooks/use-wstETH-by-stETH.ts
> +  const { data, error, isLoading, isFetching, refetch } = useQuery({
done

2024-11-24 05:33 UTC, solidovic commented on modules/web3/hooks/use-steth-contract-address.ts
> +  const { data, error, isLoading, isFetching } = useQuery({
done

2024-11-24 05:41 UTC, solidovic commented on modules/web3/hooks/use-wstETH-by-stETH.ts
> +        : shares.convertToShares(steth);
done

2024-11-24 05:41 UTC, solidovic commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +        : shares.convertToSteth(wsteth);
done

2024-11-24 05:41 UTC, solidovic commented on modules/web3/web3-provider/lido-sdk.tsx
> +      shares,
removed

2024-11-24 05:45 UTC, solidovic commented on features/settings/settings-form/settings-form.tsx
> +import { useContractAddress } from 'shared/hooks/use-contract-address';
done

2024-11-24 05:48 UTC, solidovic commented on features/withdrawals/hooks/contract/useTotalSupply.ts
> +    queryKey: ['use-total-supply', stETH],
done

2024-11-24 05:55 UTC, solidovic commented on features/wsteth/wrap/wrap-form-controls/token-amount-input-wrap.tsx
> +      isLocked={!!isApprovalNeededBeforeWrap}
done

2024-11-24 05:55 UTC, solidovic commented on features/wsteth/wrap/wrap-form-controls/submit-button-wrap.tsx
> +      isLocked={!!isLocked}
done

2024-11-24 05:57 UTC, solidovic commented on features/rewards/components/EthSymbol.tsx
> +    {ETHER_SYMBOL}
the 'ETHER_SYMBOL' moved to 'modules/web3'

2024-11-24 06:00 UTC, solidovic commented on features/rewards/hooks/useRewardsDataLoad.ts
> +    staleTime: 0,
fixed

2024-11-24 12:13 UTC, solidovic commented on config/groups/stake.ts
> +export const BALANCE_PADDING = BigInt(10000000000000000); // same as parseEther('0.01')
done

2024-11-24 12:18 UTC, solidovic commented on package.json
>      "@tanstack/react-query": "^5.51.21",
done

2024-11-24 12:24 UTC, solidovic commented on features/rewards/hooks/useRewardsDataLoad.ts
> +    cacheTime: 0,
fixed

2024-11-24 12:35 UTC, solidovic commented on features/rewards/utils/genExportData.ts
> +        balance: weiToEth(BigInt(item.balance)).toString(),
done

2024-11-24 12:49 UTC, solidovic commented on features/withdrawals/hooks/use-withdraw-request-tx-price.ts
> +    ? BigInt(permitEstimateData.gasLimit || '0')
done

2024-11-24 12:56 UTC, solidovic commented on features/withdrawals/hooks/useNftDataByTxHash.ts
> +            .read.tokenURI([Number(e.args.requestId)]);
fixed

2024-11-24 18:59 UTC, solidovic commented on modules/web3/web3-provider/web3-provider.tsx
>      <WagmiProvider config={wagmiConfig} reconnectOnMount={false}>
It was moved to 'providers/inpage-navigation.tsx' (the ConfigProvider uses to fetch the external-config with useQuery)

QueryClientProvider can be outside WagmiProvider (this is a valid structure. in the docs is just one example).

2024-11-24 19:39 UTC, solidovic commented on config/groups/web3.ts
> +export const ESTIMATE_AMOUNT = BigInt(1000000000000000); // same as parseEther('0.001')
moved to 'modules/web3/consts/tx.ts', 'cause the problem is caused by incompatibility between viem (ESM only) and Next.js 12 (next.config.mjs). temp solution

2024-11-24 19:41 UTC, solidovic commented on features/stake/stake-form/hooks.ts
> +    enabled: !!stake.core && !!stake.core.chainId,
fixed

2024-11-24 20:00 UTC, solidovic commented on features/stake/swap-discount-banner/use-swap-discount.ts
> +        return await fetchRate(config.STAKE_SWAP_INTEGRATION);
the `onError` was removed since @tanstack/react-query v5+

2024-11-24 20:28 UTC, solidovic commented on features/rewards/hooks/use-steth-eth-rate.ts
> +  const { data, error } = useQuery({
done

2024-11-24 21:10 UTC, solidovic commented on features/rewards/utils/genExportData.ts
> +        change: weiToEth(BigInt(item.change)).toString(),
done

2024-11-24 21:13 UTC, solidovic commented on features/stake/stake-form/hooks.ts
> +    queryFn: async () => {
?

2024-11-24 22:00 UTC, solidovic commented on features/stake/stake-form/use-stake.ts
> +              await onConfirm?.();
done

2024-11-25 06:45 UTC, solidovic commented on config/groups/withdrawal-queue-estimate.ts
> +  BigInt(255350);
done

2024-11-25 10:16 UTC, solidovic commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +      if (wsteth == null) return undefined;
added wsteth as bigint.
anyway, if wsteth == null (undefined) then we won't get into queryFn

2024-11-25 10:38 UTC, solidovic commented on features/stake/stake-form/use-stake.ts
> +  const txHashRef = useRef<Address | undefined>(undefined);
removed

2024-11-25 10:59 UTC, Jeday requested changes

2024-11-25 10:59 UTC, Jeday commented on shared/hooks/useLidoApr.ts
> +        const lastApr = await statistics.apr.getLastApr();
what about when your are not on mainnet?

2024-11-25 10:59 UTC, Jeday commented on shared/components/input-amount/input-amount.tsx
> +      onChange && maxValue !== undefined && maxValue > 0n
you can use browser console to quickly check your boolean condtions, if you are not sure about js bool conversions(this is okay though)

2024-11-25 10:59 UTC, Jeday commented on shared/components/allowance-data-table-row/allowance-data-table-row.tsx
> +  token: TOKENS_TO_WRAP | TOKENS_TO_WITHDRAWLS;
Not a fan of this approach, let's have a singular TOKENS enum and then narrow down with TOKEN_TO_WRAP = TOKENS.ETH | TOKENS.STETH

2024-11-25 10:59 UTC, Jeday commented on providers/ipfs-info-box-statuses.tsx
> +      return await checkRpcUrl(rpcUrl, chainId, stethAddress);
no need for `return await` and `async`, just return checkRpcUrl

2024-11-25 10:59 UTC, Jeday commented on modules/web3/hooks/use-wstETH-by-stETH.ts
> +      if (steth == null) return undefined;
do not return undefined, chagne to invariant

2024-11-25 10:59 UTC, Jeday commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +      if (wsteth == null) return undefined;
Yes, but this creates unnecessary footgun, invariants solve this by being easily detectable.

2024-11-25 10:59 UTC, Jeday commented on modules/web3/hooks/use-contract-address.ts
> +export const useContractAddress = (
I think we can make this hook sync, it will be easier for other code. IMO static addresses are okay for non-critical func. 
Also consider checking where this hook is used

2024-11-25 10:59 UTC, Jeday commented on modules/web3/consts/units.ts
> +export const ZERO = parseEther('0');
that just 0n, let's remove this const

2024-11-25 10:59 UTC, Jeday commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +const fetchGasLimitETH = async (isL2: boolean, wrap: any) => {
why any? can use LidoSDKWrap

2024-11-25 10:59 UTC, Jeday commented on features/rewards/constants.ts
> +export const ETHER = 1_000_000_000_000_000_000n;
parseEther('1')

2024-11-25 11:43 UTC, Jeday requested changes

2024-11-25 11:43 UTC, Jeday commented on features/settings/settings-form/settings-form.tsx
> +import { Address } from 'viem';
import type

2024-11-25 11:43 UTC, Jeday commented on features/stake/stake-form/hooks.ts
> +    queryFn: async () => {
we have estimateGas in sdk.stake as method

2024-11-25 11:43 UTC, Jeday commented on features/stake/stake-form/use-stake.ts
> +              txModalStages.successMultisig();
I think we DRY this between different TXs.

2024-11-25 14:11 UTC, solidovic commented on features/settings/settings-form/settings-form.tsx
> +import { Address } from 'viem';
done

2024-11-25 14:12 UTC, solidovic commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +const fetchGasLimitETH = async (isL2: boolean, wrap: any) => {
misprint

2024-11-25 14:32 UTC, solidovic commented on features/rewards/constants.ts
> +export const ETHER = 1_000_000_000_000_000_000n;
done

2024-11-25 14:32 UTC, solidovic commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +const fetchGasLimitETH = async (isL2: boolean, wrap: any) => {
done

2024-11-25 14:32 UTC, solidovic commented on modules/web3/consts/units.ts
> +export const ZERO = parseEther('0');
done

2024-11-25 14:33 UTC, solidovic commented on shared/hook-form/validation/validate-ether-amount.ts
> +import { ZERO } from 'modules/web3/consts/units';
done

2024-11-25 14:33 UTC, solidovic commented on shared/hook-form/validation/validate-ether-amount.ts
> +  if (amount <= ZERO)
done

2024-11-25 14:34 UTC, solidovic commented on shared/hooks/use-token-max-amount.ts
> +        if (maxAmount < ZERO) maxAmount = ZERO;
done

2024-11-25 14:34 UTC, solidovic commented on shared/transaction-modal/tx-stages-composed/tx-stage-operation-succeed-balance-shown.tsx
> +  ) : null;
done

2024-11-25 14:34 UTC, solidovic commented on utils/formatBalance.ts
> +  balance = ZERO,
done

2024-11-25 14:35 UTC, solidovic commented on utilsApi/nextApiWrappers.ts
> +      const contractName = METRIC_CONTRACT_ADDRESSES?.[chainId]?.[address];
removed

2024-11-25 15:07 UTC, solidovic commented on modules/web3/hooks/use-contract-address.ts
> +export const useContractAddress = (
It seems that for the moment we can leave it as is. Let's make it synchronous as soon as we need it

2024-11-25 15:14 UTC, solidovic commented on providers/ipfs-info-box-statuses.tsx
> +      return await checkRpcUrl(rpcUrl, chainId, stethAddress);
done

2024-11-25 15:16 UTC, solidovic commented on shared/components/input-amount/input-amount.tsx
> +      onChange && maxValue !== undefined && maxValue > 0n
done

2024-11-25 15:32 UTC, solidovic commented on shared/hooks/use-protocol-fee.ts
> +      !!core &&
simplified

2024-11-25 15:32 UTC, solidovic commented on shared/hooks/use-protocol-fee.ts
> +      if (!stakingRouterAddress) return;
added invariant

2024-11-25 19:45 UTC, solidovic commented on utilsApi/nextApiWrappers.ts
> +export const getFunctionSelector = (func: any): string => {
checked. seems it all

2024-11-25 19:45 UTC, solidovic commented on utilsApi/nextApiWrappers.ts
> +export const getFunctionSelector = (func: any): string => {
> https://viem.sh/docs/utilities/toFunctionSelector

done

2024-11-25 19:48 UTC, solidovic commented on utilsApi/metrics/startup-metrics.ts
> +      // You will see this on 'yarn dev'
done

2024-11-25 19:52 UTC, solidovic commented on modules/web3/hooks/use-wstETH-by-stETH.ts
> +      if (steth == null) return undefined;
removed. added a 'as bigint'

2024-11-26 07:09 UTC, Jeday requested changes

2024-11-26 07:09 UTC, Jeday commented on shared/hooks/use-protocol-fee.ts
> +      invariant(
Instead of this you can do 
`const address = await core.getContractAddress(stakingRouter)`
This is better than hook waterfall and also address is cached inside lido sdk so no extra request will be made.

2024-11-26 07:09 UTC, Jeday commented on shared/hooks/use-eth-usd.ts
>        if (!publicClientMainnet) return;
change to invariant

2024-11-26 07:09 UTC, Jeday commented on modules/web3/web3-provider/web3-provider.tsx
> +  const wagmiMainnetOnlyConfig = useMemo(() => {
Let's return {config, publicClient} because we use public client most of time anyway

2024-11-26 07:09 UTC, Jeday commented on modules/web3/web3-provider/web3-provider.tsx
> +  const wagmiMainnetOnlyConfig = useMemo(() => {
Also let's move this to separate file,as this is good scoped and self-descriptive piece of logic

2024-11-26 07:14 UTC, Jeday commented on features/stake/stake-form/use-stake.ts
> +              txModalStages.successMultisig();
It's okay for now. Might have to change this soon anyway

2024-11-26 07:16 UTC, Jeday commented on modules/web3/hooks/use-contract-address.ts
> +export const useContractAddress = (
I don't like this, because it creates hook waterfall and short undefined states everywhere it it.

2024-11-26 07:34 UTC, solidovic commented on features/stake/stake-form/hooks.ts
> +    queryFn: async () => {
using the stake.stakeEthEstimateGas

2024-11-26 07:35 UTC, solidovic commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +      if (wsteth == null) return undefined;
I'm afraid that the invariant in that place can play a cruel joke

2024-11-26 07:37 UTC, solidovic commented on shared/components/tx-link-etherscan/tx-link-etherscan.tsx
> +  txHash?: Address | Hash;
done

2024-11-26 07:38 UTC, solidovic commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +        ? l2.steth.convertToSteth(wsteth as bigint)
I'm afraid that the invariant in that place can play a cruel joke

2024-11-26 08:52 UTC, solidovic commented on features/ipfs/security-status-banner/use-remote-version.ts
>          // @ts-expect-error: it works, but typing issue
add as PublicClient
import { type PublicClient } from 'viem';
in fixes PR

2024-11-26 09:00 UTC, solidovic commented on features/stake/stake-form/hooks.ts
> +    // select: (gasLimit) => applyGasLimitRatio(gasLimit),
in fixes PR

2024-11-26 09:12 UTC, solidovic commented on features/ipfs/security-status-banner/use-remote-version.ts
> +        const resolverAddress = await getEnsResolver(publicClient, {
done as PublicClient

2024-11-26 12:51 UTC, solidovic commented on features/ipfs/security-status-banner/use-remote-version.ts
> +        const resolverAddress = await getEnsResolver(publicClient, {
not actual

2024-11-26 12:57 UTC, solidovic commented on modules/web3/hooks/use-wstETH-by-stETH.ts
> +        ? l2.steth.convertToShares(steth as bigint)
done with invariant

2024-11-26 12:57 UTC, solidovic commented on shared/hooks/use-eth-usd.ts
>        if (!publicClientMainnet) return;
done with invariant

2024-11-26 12:58 UTC, Jeday commented on modules/web3/hooks/use-stETH-by-wstETH.ts
> +        ? l2.steth.convertToSteth(wsteth as bigint)
Not sure what you mean? 0n, this is expected to give clear error

2024-11-26 13:27 UTC, Jeday submitted a review, later dismissed

2024-11-27 07:11 UTC, Jeday submitted a review, later dismissed

2024-11-27 08:05 UTC, Jeday approved these changes

2024-11-27 08:10 UTC, Jeday commented
LGTM

2024-11-27 10:06 UTC, DiRaiks commented on config/external-config/use-external-config-context.ts
>    const fallbackData = useFallbackManifestEntry(
```suggestion
  const fallbackData = useFallbackManifestEntry(
  prefetchedManifest,
  defaultChain,
  )
```

2024-11-27 10:43 UTC, Jeday submitted a review, later dismissed

2024-11-27 11:46 UTC, DiRaiks commented on features/rewards/hooks/useRewardsDataLoad.ts
> +      // The 'react-query' has AbortController support built in,
Does it work when changing table pages on the rewards page?

2024-11-27 11:47 UTC, DiRaiks commented on features/rewards/utils/addressValidation.ts
> +export const isValidAddress = (address: string) => isAddress(address);
It looks like this function doesn't make sense since it's just a wrapper over another function. Why not use `isAddress` directly?

2024-11-27 11:58 UTC, DiRaiks commented on features/settings/settings-form/settings-form.tsx
> +        stethAddress as Address | null,
I think there is no needs additional types. Just `stethAddress`

2024-11-27 12:14 UTC, DiRaiks commented on features/stake/stake-form/use-stake.ts
> +              const [, balance] = await Promise.all([
@Jeday Could we get info about the balance from the TX result?

2024-11-27 12:36 UTC, DiRaiks commented on features/withdrawals/claim/form/requests-list/request-item.tsx
> +      'withdrawalQueue' as LIDO_CONTRACT_NAMES,
Looks like type bug with LIDO_CONTRACT_NAMES.
I think we can use it like LIDO_CONTRACT_NAMES.withdrawalQueue
cc @Jeday

2024-11-27 12:38 UTC, solidovic commented on features/rewards/hooks/useRewardsDataLoad.ts
> +      // The 'react-query' has AbortController support built in,
Yes it does, because when we changes the table (pagination) the `queryKey: ['rewards-data', address, apiRewardsUrl]` changes too (skip=<number>&limit=<number> in the apiRewardsUrl)

2024-11-27 16:57 UTC, DiRaiks commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +  if (isL2) return 0n;
Why for l2 is always 0n?

2024-11-27 17:12 UTC, solidovic commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +  if (isL2) return 0n;
on L2 (Optimism right now) we can wrap only stETH, on L1 we can wrap (stETH and ETH)

2024-11-27 17:13 UTC, solidovic commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +  if (isL2) return 0n;
returning this value is like a stub

2024-11-28 07:30 UTC, Jeday submitted a review, later dismissed

2024-11-28 07:37 UTC, Jeday commented on features/stake/stake-form/use-stake.ts
> +              const [, balance] = await Promise.all([
Considering we are refetching other balance data anyway, I think this is okay.

2024-11-28 07:38 UTC, Jeday commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +  if (isL2) return 0n;
Can we avoid calling fetchGasLimitETH if isL2:true? This would better indicate how this code works.

2024-11-28 07:39 UTC, Jeday commented on features/withdrawals/claim/form/requests-list/request-item.tsx
> +      'withdrawalQueue' as LIDO_CONTRACT_NAMES,
Completely right, forgot this is enum. Let's do this instead.

2024-11-28 07:42 UTC, Jeday commented on features/withdrawals/claim/form/requests-list/request-item.tsx
> +      'withdrawalQueue' as LIDO_CONTRACT_NAMES,
Sidenote, we should take a firm stance on enums in our code style. We have a mix of enums, const enums, objects and string type literals in our codebase due to TS enums being wacky.

2024-11-28 09:41 UTC, solidovic commented on features/rewards/utils/addressValidation.ts
> +export const isValidAddress = (address: string) => isAddress(address);
done

2024-11-28 11:59 UTC, solidovic commented on features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
> +  if (isL2) return 0n;
done (not to call the fetchGasLimitETH for l2)

2024-11-29 03:12 UTC, DiRaiks commented on utilsApi/contractAddressesMetricsMap.ts
> +        getRateTokenAddress(chainId, LIDO_TOKENS.steth) ?? null,
It seems to me that the name of the utility does not quite correspond to what it does. And therefore this file raises questions - why do we need a Rate token.
The function is similar to simply getting the token address by its name

2024-11-29 03:16 UTC, DiRaiks approved these changes
LGTM with the exception of small comments and improvement tasks, which are better done after this PR. 
The huge work!

2024-12-02 07:25 UTC, Jeday approved these changes

2024-12-02 16:49 UTC, DiRaiks submitted a review, later dismissed

2024-12-03 06:16 UTC, Jeday submitted a review, later dismissed

2024-12-03 10:34 UTC, solidovic commented on utilsApi/contractAddressesMetricsMap.ts
> +        getRateTokenAddress(chainId, LIDO_TOKENS.steth) ?? null,
done (getRateTokenAddress --> getTokenAddress)

2024-12-04 09:19 UTC, solidovic commented on features/withdrawals/claim/form/requests-list/request-item.tsx
> +      'withdrawalQueue' as LIDO_CONTRACT_NAMES,
https://github.com/lidofinance/ethereum-staking-widget/pull/555

2024-12-04 09:20 UTC, solidovic commented on utilsApi/contractAddressesMetricsMap.ts
> +        getRateTokenAddress(chainId, LIDO_TOKENS.steth) ?? null,
https://github.com/lidofinance/ethereum-staking-widget/pull/553

2024-12-04 09:22 UTC, Jeday approved these changes

2024-12-04 09:37 UTC, DiRaiks submitted a review, later dismissed

2024-12-05 07:13 UTC, Jeday approved these changes

2024-12-06 06:41 UTC, Jeday approved these changes

2024-12-09 10:37 UTC, Jeday approved these changes

2024-12-09 10:58 UTC, merged