feat: faq via cms
lidofinance/ethereum-staking-widget pull request #56
Opened 2023-09-20 08:11 UTC by solidovic

### Description

- Integrate [FAQ package](https://www.npmjs.com/package/@lidofinance/ui-faq) for **all pages FAQ** (works with Next SRR, Client Side, IPFS version).

- Matomo:

   - Events to matomo send by another way (actual only for code review).

   - A matomo event generated by template `<project_name>_faq_<page_id>_<question_id>_<link_content>`
   For example for `Request tab` link: event will be `eth_widget_faq_Withdrawals_Claim_How_Do_I_Withdraw_Request_tab`

###  FAQ content to CMS

see PR: 
   - Stake Page: https://github.com/lidofinance/lido-content/pull/66

   - Wrap Page: https://github.com/lidofinance/lido-content/pull/68

   - Withdrawals Page Claim: https://github.com/lidofinance/lido-content/pull/69

   - Withdrawals Page Request: https://github.com/lidofinance/lido-content/pull/70

### Code review notes

- Needs approve new matomo event in all `FAQ` blocks with @mariyamuziko, 'cause now they are generated by template.

- Needs add all `FAQ` blocks content to https://github.com/lidofinance/lido-content via Lido CMS. More info you can find by me (@solidovic) or @mariyamuziko

- Check a both using of `mode` and `faqList` and `revalidate` in `getStaticProps` on `pages/wrap/[[...mode]].tsx`.

### Testing notes

Needs to click all links on `FAQ` blocks  and make sure events send to Matomo.

Check on IPFS version.

### Related PRs
- https://github.com/lidofinance/lido-cms/pull/27
- https://github.com/lidofinance/ethereum-staking-widget/pull/59
- https://github.com/lidofinance/lido-content/pull/52
- Stake Page: https://github.com/lidofinance/lido-content/pull/66
- Wrap Page: https://github.com/lidofinance/lido-content/pull/68
- Withdrawals Page Claim: https://github.com/lidofinance/lido-content/pull/69
- Withdrawals Page Request: https://github.com/lidofinance/lido-content/pull/70

**UPDATE:** after we decided that wants split FAQ by page:
- warehouse pkg update
- https://github.com/lidofinance/lido-cms/pull/28

### Checklist:

- [X] Checked the changes locally.
- [X] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-10-02 11:42 UTC, Jeday requested changes

2023-10-02 11:42 UTC, Jeday commented on features/home/stake-faq/stake-faq.tsx
> +  useEffect(() => {
At first glance, seems like this would not render on server. Am I missing something? Can we move `getFAQ` to `getStaticProps` and pass faq as page props?

2023-10-02 11:42 UTC, Jeday commented on features/home/stake-faq/stake-faq.tsx
> +            (page: PageFAQ) => page['identification'] === pageIdentification,
Why request all pages and then filter? Can we request separate pages? If this is dictated by CMS perhaps we should change it while we can.

2023-10-02 12:04 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +            (page: PageFAQ) => page['identification'] === pageIdentification,
We can't in current implementation. Looks like we can change it, but needs more research and sync with UI-team.

2023-10-03 06:58 UTC, Jeday commented on features/home/stake-faq/stake-faq.tsx
> +  useEffect(() => {
For IPFS we can show potentially old content at start, but have async logic that will fetch FAQ in background and update if needed. If we can have some sort of content hash comparing solution that would be perfect for network requests load.

2023-10-03 07:00 UTC, Jeday commented on features/home/stake-faq/stake-faq.tsx
> +            (page: PageFAQ) => page['identification'] === pageIdentification,
I see, as this task is not very urgent for release I would love to see this resolved as not to add tech debt.

2023-10-10 20:53 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +  useEffect(() => {
Moved to getStaticProps without support of IPFS

2023-10-10 20:56 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +            (page: PageFAQ) => page['identification'] === pageIdentification,
Not resolved. The current realities let to postpone to tech debt.

2023-10-11 07:21 UTC, DiRaiks commented on pages/index.tsx
> +    // noop
Need a log here.

2023-10-11 13:20 UTC, solidovic commented on pages/index.tsx
> +    // noop
Add warn logs, use axios with metrics and timeout.

'@lidofinance/ui-faq' is require axios, which is alterable.

2023-10-11 13:35 UTC, Jeday requested changes

2023-10-11 13:35 UTC, Jeday commented on features/home/stake-faq/stake-faq.tsx
> +interface StakeFaqProps {
Why not type? Here difference is minimal but we use type for props everywhere.

2023-10-11 13:50 UTC, solidovic commented on utils/axios/clientAxios.ts
> +export const createClientAxios = (axiosConfig?: CreateAxiosDefaults) => {
Thank you. The ClientAxios really not needed now. But I something remember (maybe I wrong) that we have plan use Axios (repeat maybe I wrong). Looks like I am wrong.

About serverAxios: `getFAQ` from `@lidofinance/ui-faq` is require Axios, just `fetch` not supported.

We can to use `fetch` without `getFAQ`, we should use `parseYamlFileWithMdContent` instead of.

2023-10-11 14:05 UTC, solidovic commented on features/withdrawals/withdrawals-tabs.tsx
> +        <Request faqList={faqListRequest} />
either I don't understand your thoughts

2023-10-11 14:09 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +interface StakeFaqProps {
Done

2023-10-11 17:14 UTC, DiRaiks commented on package.json
> +    "axios": "^1.5.0",
Why do you need axios?
Let's try to use fetch only.

2023-11-21 09:29 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +            (page: PageFAQ) => page['identification'] === pageIdentification,
FAQ was divided by pages

2023-11-21 09:29 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +            (page: PageFAQ) => page['identification'] === pageIdentification,
Comment can be closed

2023-11-21 09:29 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +  useEffect(() => {
Added SSR

2023-11-21 09:30 UTC, solidovic commented on utils/axios/clientAxios.ts
> +export const createClientAxios = (axiosConfig?: CreateAxiosDefaults) => {
Removed axios

2023-11-21 09:31 UTC, solidovic commented on features/home/stake-faq/stake-faq.tsx
> +    <NoSSRWrapper>
resolved

2023-11-21 09:31 UTC, solidovic commented on pages/index.tsx
> +    // noop
added console.warn(...)

2023-11-22 10:28 UTC, Jeday approved these changes

2023-12-18 08:02 UTC, Jeday requested changes

2023-12-18 08:02 UTC, Jeday commented on utilsApi/faq.ts
> +  console.debug(`[fetchFaqSSR] Fetched the '${path}' from CMS was successes!`);
`Successfully fetched ...`

2023-12-18 08:29 UTC, DiRaiks commented on .env.example
> +FAQ_CONTENT_PART_OF_URL=
Why "PART_OF_URL"? Isn't it possible to call it "FAQ_CONTENT_BASE_PATH" like other?

2023-12-18 08:29 UTC, DiRaiks commented on .gitignore
> +/public/ethereum-staking-widget/
Why this is needed?

2023-12-18 08:29 UTC, DiRaiks commented on features/stake/stake-page.tsx
> +      <StakeFaq pageFAQ={pageFAQ ?? undefined} eTag={faqETag ?? undefined} />
lets use `null` or `undefined`, not both.

2023-12-20 14:21 UTC, solidovic commented on .gitignore
> +/public/ethereum-staking-widget/
temply. removed.

2023-12-21 09:34 UTC, solidovic commented on shared/hooks/use-faq-on-client.ts
> +export const useFetchFaqOnClientIfETagWereChanged = (
done

2023-12-21 09:34 UTC, solidovic commented on env-dynamics.mjs
> +export const faqContentPartOfUrl = process.env.FAQ_CONTENT_PART_OF_URL;
done

2023-12-21 09:34 UTC, solidovic commented on utilsApi/faq.ts
> +  console.debug(`[fetchFaqSSR] Fetched the '${path}' from CMS was successes!`);
done

2023-12-21 09:34 UTC, solidovic commented on .env.example
> +FAQ_CONTENT_PART_OF_URL=
done

2023-12-26 12:01 UTC, Jeday approved these changes

2024-01-16 13:17 UTC, DiRaiks approved these changes

2025-04-08 10:55 UTC, closed without merging