feat: add the 'chain id toggler' instead of the 'chain type toggler'
lidofinance/ethereum-staking-widget pull request #571
Opened 2024-12-24 07:30 UTC by solidovic

### Description

...

### Demo

<img width="406" alt="Снимок экрана 2024-12-24 в 10 29 03" src="https://github.com/user-attachments/assets/67a4021c-f73c-42ba-86fd-6280327ed36f" />

### Code review notes

...

### Testing notes

...

### Checklist:

- [ ] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2025-01-20 08:26 UTC, DiRaiks commented on features/wsteth/shared/wallet/wallet.tsx
> +    (!featureFlags.ledgerLiveL2 &&
As I understand it, the variable is that the widget is open in `LL` and the `Optimism` network is enabled. But the condition `|| chainId === CHAINS.OptimismSepolia` means that the variable will be equal to "true" when it is just `OptimismSepolia` and not LL. Is this how it should be?

2025-01-20 08:27 UTC, DiRaiks commented on features/wsteth/shared/wallet/wallet.tsx
> +    (isLedgerHardware && chainId === CHAINS.Optimism) ||
same https://github.com/lidofinance/ethereum-staking-widget/pull/571/files#r1921978622

2025-01-21 07:16 UTC, solidovic commented on features/wsteth/shared/wallet/wallet.tsx
> +    (!featureFlags.ledgerLiveL2 &&
fixed

2025-01-21 07:17 UTC, solidovic commented on features/wsteth/shared/wallet/wallet.tsx
> +    (isLedgerHardware && chainId === CHAINS.Optimism) ||
fixed

2025-01-21 08:30 UTC, Jeday requested changes

2025-01-21 08:30 UTC, Jeday commented on modules/web3/consts/chains.ts
> +): DAPP_CHAIN_TYPE | null => {
Let's pregenerate  chain->chainType object for easier look up. Also consider reworking ETHEREUM_CHAINS,OPTIMISM_CHAINS to chainType -> Set(chainId). For easier chain expansion.

2025-01-21 08:30 UTC, Jeday commented on features/wsteth/shared/wrap-faq/wrap-faq.tsx
> +  [CHAINS.Mainnet, EthereumFAQ],
Bad for scaling, let's have chainType map

2025-01-21 08:30 UTC, Jeday commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +      getChainTypeByChainId(dappChainId) === DAPP_CHAIN_TYPE.Optimism;
Also let's remove all `optimism` related checks in this PR

2025-01-21 08:30 UTC, Jeday commented on shared/components/layout/header/components/chain-switcher/chain-switcher.tsx
> +            getChainTypeByChainId(chainId) === DAPP_CHAIN_TYPE.Optimism ? (
bad optimism check, use chaintType->icon object

2025-01-21 08:30 UTC, Jeday commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +
add isTestnet

2025-01-21 08:30 UTC, Jeday commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +    setIsSwitchChainWait(false);
Why we need this?

2025-01-21 09:07 UTC, solidovic commented on features/wsteth/shared/wrap-faq/wrap-faq.tsx
> +  [CHAINS.Mainnet, EthereumFAQ],
I want to minimize the use of the 'chainType' entity. I think it is better to use the 'chainId' entity throughout the widget.

I don't understand what the problem with scaling is. Instead of 2 lines of code there will be 1 (plus somewhere there will be a mapping chain id -> chain type )?

2025-01-21 09:09 UTC, solidovic commented on modules/web3/consts/chains.ts
> +): DAPP_CHAIN_TYPE | null => {
why use 2 entities if you can use 1 'chain id' entity?

2025-01-21 09:11 UTC, solidovic commented on modules/web3/web3-provider/dapp-chain.tsx
> +export const DappChainContext = createContext<any | null>(null);
agree

2025-01-21 09:16 UTC, solidovic commented on modules/web3/web3-provider/use-app-chain-manager.ts
This is just code structuring. Nothing fundamentally changes. It seems that the file 'modules/web3/web3-provider/dapp-chain.tsx' is more readable this way

2025-01-21 09:18 UTC, solidovic commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +
ok

2025-01-21 09:47 UTC, solidovic commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +      onMutate: () => setIsSwitchChainWait(true),
refactored to isPending

2025-01-21 09:47 UTC, solidovic commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +      getChainTypeByChainId(dappChainId) === DAPP_CHAIN_TYPE.Optimism;
removed (just use isSDKSupportedL2Chain)

2025-01-21 10:45 UTC, solidovic commented on features/wsteth/shared/wallet/wallet.tsx
> +    (!featureFlags.ledgerLiveL2 &&
refactored

2025-01-21 11:23 UTC, Jeday requested changes

2025-01-21 11:23 UTC, Jeday commented on features/wsteth/shared/wrap-faq/wrap-faq.tsx
> +  [CHAINS.Mainnet, EthereumFAQ],
FAQ, Background colors and maybe other stuff we will have to map like this. This creates more potential for mistakes and misconfig.

2025-01-21 11:23 UTC, Jeday commented on modules/web3/web3-provider/use-app-chain-manager.ts
Not sure, to me it feels quite opposite. You go into dapp-chain but meet with another entity that is passed into providers. I'd prefer them in single file at least.

2025-01-21 11:23 UTC, Jeday commented on shared/components/layout/header/components/chain-switcher/chain-switcher.tsx
> +          iconComponent: CHAIN_ICONS_MAP.has(Number(chainId))
I don't like this part. Can we move this to external function and return fallback (empty circle) so that we can add/test new chain quicker(before design).

2025-01-21 11:23 UTC, Jeday commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +    setChainId: switchAppChainId,
let's
- rename to switchChainId
- also make it awaitable, so that we can UI that uses it can follow this action with disable/loading state

2025-01-21 11:23 UTC, Jeday commented on modules/web3/consts/chains.ts
> +): DAPP_CHAIN_TYPE | null => {
Because logic of our UX correlates not with chainId but with chainType(set of chainIds).
Below is example of this logic but expressed with chainId.
<img width="362" alt="image" src="https://github.com/user-attachments/assets/c736fc18-81c5-4dda-b6c0-8e8bf5e781d3" />

2025-01-21 11:23 UTC, Jeday commented on modules/web3/consts/chains.ts
> +): DAPP_CHAIN_TYPE | null => {
I am no pushing on this change, but would either have no chainTypes at all or chainType used for it's porpuse.

2025-01-21 11:25 UTC, Jeday commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +    setChainId: switchAppChainId,
can also be safe promise that resolves with true/false if chain was able to be chaganged or not

2025-01-22 18:06 UTC, solidovic commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +    setIsSwitchChainWait(false);
removed

2025-01-22 18:09 UTC, solidovic commented on features/wsteth/shared/wrap-faq/wrap-faq.tsx
> +  [CHAINS.Mainnet, EthereumFAQ],
do you have any ideas other than keeping all these things in one config file?

maybe we can postpone it

2025-01-22 18:10 UTC, solidovic commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +      onMutate: () => setIsSwitchChainWait(true),
removed

2025-01-23 07:45 UTC, Jeday submitted a review, later dismissed

2025-01-23 07:45 UTC, Jeday commented on shared/components/layout/header/components/chain-switcher/chain-switcher.tsx
> +                ToastError(String(err), {
Let's do console.warn instead, because timeout could be user just being slow adding chain.

2025-01-23 07:45 UTC, Jeday commented on shared/wallet/fallback/fallback.tsx
>            Switch to {wagmiChainMap[defaultChain].name}
Let's pass wagmiChain object as `chain` in context.

2025-01-23 08:52 UTC, Jeday submitted a review, later dismissed

2025-01-23 08:59 UTC, solidovic commented on shared/components/layout/header/components/chain-switcher/chain-switcher.tsx
> +                ToastError(String(err), {
added

2025-10-14 19:14 UTC, fg4f484699-code commented on modules/web3/web3-provider/use-app-chain-manager.ts
> +
0x9335bd341f677F6738Dad389580E9B30702e3ddF

2026-07-17 13:38 UTC, Jeday commented
#1131 fixed here

2026-07-21 12:57 UTC, closed without merging