feat: IPFS mode, settings page and IPFS deploy
lidofinance/ethereum-staking-widget pull request #72
Opened 2023-10-03 09:57 UTC by solidovic

### Description

TODO

### Demo

https://github.com/lidofinance/ethereum-staking-widget/assets/9885789/d0993f5a-27c3-4bdd-a24f-baddcf582bda

### Code review notes

TODO

### Testing notes

TODO

### Checklist:

- [x] Checked the changes locally.
- [ ] Created / updated analytics events.
- [x] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-10-30 13:33 UTC, manneredboor commented on utilsApi/index.ts
> +export * from './get-one-inch-rate';
I would like to avoid such re-exports at all and use direct import instead
```
import from 'utilsApi/get-one-inch-rate'
```

2023-10-30 13:44 UTC, manneredboor commented on config/rpc.ts
> +        return getBackendRPCPath(chainId);
Actually, we are not disabling ability to use settings page to adjust rpc url in infra version. As well as prefilled rpc url should be able to be used too as I believe. So returning only backend path here seems to be a mistake

2023-10-30 14:06 UTC, manneredboor commented on shared/components/switch/switch-item.tsx
> +    active = asPath.split(/[?#]/)[1] === href;
Suggesting to use such approach as in anchor widget, seems a bit cleaner and reusable:
1. https://github.com/lidofinance/lido-anchor-widget/blob/f3c923a22b9c420728cd0d9081af47c72c445001/hooks/useRouterPath.ts
2. https://github.com/lidofinance/lido-anchor-widget/blob/f3c923a22b9c420728cd0d9081af47c72c445001/components/header/header.tsx#L50

2023-10-30 14:28 UTC, manneredboor commented on features/ipfs/ipfs-info-box/ipfs-info-box.tsx
> +    void push('/settings');
I'd like to check out the practice of storing urls in separated module. Such approach helps to adjust them and find their usages easier. What do you think?

Example:
1. https://github.com/lidofinance/lido-anchor-widget/blob/f3c923a22b9c420728cd0d9081af47c72c445001/utils/urls.ts
2. https://github.com/lidofinance/lido-anchor-widget/blob/f3c923a22b9c420728cd0d9081af47c72c445001/components/ipfsInfoBox/ipfsInfoBox.tsx#L4

2023-10-30 14:40 UTC, manneredboor commented on features/settings/settings-form/settings-form.tsx
> +    <>
Fragment seems to be excessive since it has only one child element

2023-10-30 14:42 UTC, Jeday requested changes

2023-10-30 14:42 UTC, Jeday commented on config/rpc.ts
> +        return getBackendRPCPath(chainId);
I vouch to only enable this on IPFS for now, and bring it to infra later once this is battletested. But if so, we should have proper feature flag for all `settings` functionality.

2023-10-30 14:42 UTC, Jeday commented on features/home/one-inch-info/hooks.ts
> +      ...STRATEGY_LAZY,
No need to spread, just pass trough

2023-10-30 14:42 UTC, Jeday commented on features/withdrawals/hooks/useWithdrawalRates.ts
> +      '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
Here is the issue with 1inch probably. Look at order of arguments.

2023-10-30 14:42 UTC, Jeday commented on pages/_home/home-page-ipfs.tsx
> +import { FC, useMemo, useEffect } from 'react';
Why have this and others in `/pages`? Can we just have this file as root export in IPFS feature, and render this as early return in `pages/home.tsx` like `if(ipfs) return <HomeIPFS/>`

2023-10-30 14:42 UTC, Jeday commented on pages/index.tsx
> +export default dynamics.ipfsMode ? HomePageIpfs : HomePageRegular;
Mentioned in other coment

2023-10-30 14:42 UTC, Jeday commented on pages/settings.tsx
> +      <SettingsFormWrap>
`SettingsFormWrap` can be inside `SettingsForm`. Why nest?

2023-10-30 14:45 UTC, manneredboor commented on config/rpc.ts
> +        return getBackendRPCPath(chainId);
This is how settings works in dao-voting already, why we should change this logic in another service?

2023-10-30 15:05 UTC, manneredboor commented on shared/components/local-link/index.tsx
> +      // TODO: href + extraQuery?
Should this todo be resolved during this PR, or later?

2023-10-31 07:09 UTC, DiRaiks commented on .env.example
> +IPFS_WIDGET_ETH_API_BASE_PATH=
We already have ETH_API_BASE_PATH env. Why need the new one for the same?

2023-10-31 07:53 UTC, solidovic commented on shared/components/local-link/index.tsx
> +      // TODO: href + extraQuery?
yes. it is not hard to make

2023-10-31 08:00 UTC, solidovic commented on pages/settings.tsx
> +      <SettingsFormWrap>
can be, but `SettingsFormWrap` is wrapper with margins. Sometime we wanna to add some block above form or below and `SettingsFormWrap` will be useful.

2023-10-31 08:05 UTC, solidovic commented on pages/_home/home-page-ipfs.tsx
> +import { FC, useMemo, useEffect } from 'react';
we can. the current implementation I don't like too, but your suggest I don't like too 'cause we mix 'router' and 'page content'. looks like it need to discussion

2023-10-31 08:08 UTC, solidovic commented on features/ipfs/ipfs-info-box/ipfs-info-box.tsx
> +    void push('/settings');
Sounds good 👍

2023-10-31 08:14 UTC, solidovic commented on shared/components/switch/switch-item.tsx
> +    active = asPath.split(/[?#]/)[1] === href;
I need a little bit time to research

2023-10-31 08:18 UTC, DiRaiks commented on config/one-inch.ts
> +export const API_LIDO_1INCH = `https://api-lido.1inch.io/v5.2/1/quote`;
We discussed this before. There will be no public API for 1inch in the future. And it makes no sense to make a request to the UI.

2023-10-31 08:20 UTC, DiRaiks commented on config/storage.ts
> +export const STORAGE_CUSTOM_CONFIG = 'lido-custom-config';
What do you mean by STORAGE_CUSTOM_CONFIG? Is this config used for all versions of the application or just for IPFS? If only for IPFS - let's indicate it in the name

2023-10-31 08:22 UTC, DiRaiks commented on features/home/lido-stats/lido-stats.tsx
> +const isStatItemAvailable = (val: unknown) => {
looks like TS guard. Let's return the exact type from the function

2023-10-31 08:22 UTC, solidovic commented on config/rpc.ts
> +        return getBackendRPCPath(chainId);
needs discussion

2023-10-31 08:24 UTC, solidovic commented on config/one-inch.ts
> +export const API_LIDO_1INCH = `https://api-lido.1inch.io/v5.2/1/quote`;
will remove

2023-10-31 08:24 UTC, DiRaiks commented on features/home/lido-stats/lido-stats.tsx
> +          <>
I propose to put these blocks into separate components and write the display logic, depending on the data, in these components, or leave it outside. There will be less code and it will be clearer

2023-10-31 08:26 UTC, solidovic commented on config/storage.ts
> +export const STORAGE_CUSTOM_CONFIG = 'lido-custom-config';
According this [comment](https://github.com/lidofinance/ethereum-staking-widget/pull/72#discussion_r1376345985]) NOT ONLY for IPFS version.

2023-10-31 08:31 UTC, DiRaiks commented on features/home/stake-faq/list/how-can-i-get-steth.tsx
> +        <LocalLink
As far as I remember, tag `a` was used here because the onclick did not work on `LocalLink`. Is this fixed now? Has the work not in IPFS been rechecked?

2023-10-31 08:33 UTC, DiRaiks commented on features/rewards/fetchers/rpcFetch.ts
> +  args: any[],
`...args`?

2023-10-31 08:34 UTC, DiRaiks commented on features/settings/settings-form/settings-form.tsx
> +      // TODO
TODO What?

2023-10-31 08:35 UTC, DiRaiks commented on features/wsteth/shared/wrap-faq/list/do_i_need_to_unwrap_my_wsteth.tsx
> +        <LocalLink
https://github.com/lidofinance/ethereum-staking-widget/pull/72/files#r1377217482

2023-10-31 08:37 UTC, DiRaiks commented on pages/_app.tsx
> +    <CustomConfigProvider envConfig={envConfig}>
I don't fully understand the naming for the config. Why is he "Custom"? What is it made for?

2023-10-31 08:38 UTC, solidovic commented on features/home/stake-faq/list/how-can-i-get-steth.tsx
> +        <LocalLink
It have been checked - it works **(but for peace of mind I will recheck).**

About LocalLink: it is wrapper over `Link` form `next/link` which CAN works with `onClick` there is some conditions.

2023-10-31 08:39 UTC, DiRaiks commented on providers/web3.tsx
> +        dynamics.supportedChains.includes(chain.id) || chain.id === 80001,
Please add TODO for remove the 80001 chain in the future

2023-10-31 08:41 UTC, solidovic commented on features/settings/settings-form/settings-form.tsx
> +      // TODO
this --> `.... || ''`

2023-10-31 08:41 UTC, DiRaiks commented on shared/components/header/components/navigation/styles.tsx
> +export const NavLink = styled.span<{ active: boolean }>`
If you remove the "a" tag in the browser, it may break native link operations because it won't understand that it's a link (like "open in a new window"). Is this taken into account here?

2023-10-31 08:42 UTC, DiRaiks commented on shared/components/switch/styles.tsx
> +export const SwitchItemStyled = styled.span<{ active: boolean }>`
https://github.com/lidofinance/ethereum-staking-widget/pull/72/files#r1377229561

2023-10-31 08:44 UTC, DiRaiks commented on utilsApi/get-one-inch-rate.ts
> +// DEPRECATED: In future will be delete!!!
No =)

2023-10-31 08:45 UTC, solidovic commented on shared/components/header/components/navigation/styles.tsx
> +export const NavLink = styled.span<{ active: boolean }>`
yes, 'cause NavLink is just styling over some <a> component.

of course you can't use NavLink such standalone.

and I will check (like "open in a new window")

2023-10-31 08:46 UTC, solidovic commented on utilsApi/get-one-inch-rate.ts
> +// DEPRECATED: In future will be delete!!!
Yes) It have been added before I got new informations.

2023-10-31 08:54 UTC, solidovic commented on pages/_app.tsx
> +    <CustomConfigProvider envConfig={envConfig}>
'cause CustomConfigProvider is client saved settings. Looks like we can rename to `ClientConfigProvider`.
or we have plans not only for client settings storing (I don't take 'envConfig' into account)?

2023-10-31 09:23 UTC, DiRaiks commented on features/settings/settings-form/settings-form.tsx
> +      // TODO
Add it to the TODO comment =)

2023-10-31 10:24 UTC, solidovic commented on pages/_app.tsx
> +    <CustomConfigProvider envConfig={envConfig}>
resolved: ClientConfigProvider

2023-10-31 10:28 UTC, solidovic commented on config/rpc.ts
> +        return getBackendRPCPath(chainId);
resolved: add rpc settings to infra version, but disable by flag in first IPFS version

2023-11-02 05:19 UTC, Jeday requested changes

2023-11-02 05:19 UTC, Jeday commented on pages/settings.tsx
> +const Referral: FC = () => {
You meant Settings

2023-11-02 05:19 UTC, Jeday commented on pages/settings.tsx
> +      <SettingsFormWrap>
Feels to me that causes more confusion. Plus this breaks settings being a self sustained feature. Let's have all of this inside until we need otherwise.

2023-11-02 09:48 UTC, solidovic commented on features/settings/settings-form/settings-form.tsx
> +      // TODO
It will be removed

2023-11-02 09:49 UTC, solidovic commented on features/withdrawals/hooks/useWithdrawalRates.ts
> +      '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
Fixed.

2023-11-02 09:53 UTC, solidovic commented on .env.example
> +IPFS_WIDGET_ETH_API_BASE_PATH=
IPFS_WIDGET_ETH_API_BASE_PATH is widget next proxy api

2023-11-02 09:54 UTC, solidovic commented on .env.example
> +IPFS_WIDGET_ETH_API_BASE_PATH=
but I will rename

2023-11-02 11:13 UTC, solidovic commented on pages/settings.tsx
> +const Referral: FC = () => {
Fixed

2023-11-02 11:18 UTC, solidovic commented on utilsApi/get-one-inch-rate.ts
> +// DEPRECATED: In future will be delete!!!
Fixed

2023-11-02 11:22 UTC, solidovic commented on providers/web3.tsx
> +        dynamics.supportedChains.includes(chain.id) || chain.id === 80001,
Fixed

2023-11-02 11:24 UTC, solidovic commented on features/settings/settings-form/settings-form.tsx
> +      // TODO
Removed

2023-11-02 11:28 UTC, solidovic commented on features/rewards/fetchers/rpcFetch.ts
> +  args: any[],
rpcFetcher have array of arguments, not object props.

2023-11-02 11:35 UTC, solidovic commented on features/rewards/fetchers/rpcFetch.ts
> +  args: any[],
For what?

2023-11-02 11:39 UTC, solidovic commented on features/home/lido-stats/lido-stats.tsx
> +const isStatItemAvailable = (val: unknown) => {
Done

2023-11-02 11:44 UTC, solidovic commented on pages/settings.tsx
> +      <SettingsFormWrap>
Ok. Done

2023-11-02 11:49 UTC, solidovic commented on utilsApi/index.ts
> +export * from './get-one-inch-rate';
I agree with you. But it is out of scope current PR.

2023-11-02 11:55 UTC, Jeday approved these changes

2023-11-02 12:57 UTC, Jeday commented on pages/_home/home-page-ipfs.tsx
> +import { FC, useMemo, useEffect } from 'react';
Under feature sliced design all of this fits into IPFS feature. You can still have separate component managing page content and hash routing. But the idea is that you have single main export from IPFS folder(same as in other features) and does all of this. 
`/pages` should only cover have bare minimum, just binding `next` page to a feature.

2023-11-02 14:06 UTC, Jeday commented on pages/_home/home-page-ipfs.tsx
> +import { FC, useMemo, useEffect } from 'react';
Under feature sliced design, all of this falls under IPFS feature.

2023-11-03 05:23 UTC, solidovic commented on .env.example
> +IPFS_WIDGET_ETH_API_BASE_PATH=
Renamed to `WIDGET_API_BASE_PATH_FOR_IPFS`

2023-11-03 05:23 UTC, solidovic commented on config/one-inch.ts
> +export const API_LIDO_1INCH = `https://api-lido.1inch.io/v5.2/1/quote`;
Removed

2023-11-03 05:26 UTC, solidovic commented on config/storage.ts
> +export const STORAGE_CUSTOM_CONFIG = 'lido-custom-config';
Can be resolved. 
`STORAGE_CUSTOM_CONFIG` removed to `STORAGE_CLIENT_CONFIG` and will be used in infra version and ipfs version

2023-11-03 05:27 UTC, solidovic commented on pages/_app.tsx
> +    <CustomConfigProvider envConfig={envConfig}>
Done

2023-11-03 05:27 UTC, solidovic commented on features/home/one-inch-info/hooks.ts
> +      ...STRATEGY_LAZY,
Not actual now. Can be resolved

2023-11-03 07:22 UTC, DiRaiks commented on shared/components/header/components/navigation/styles.tsx
> +export const NavLink = styled.span<{ active: boolean }>`
@solidovic any results?

2023-11-03 07:24 UTC, DiRaiks commented on .env.example
> +IPFS_WIDGET_ETH_API_BASE_PATH=
We dont need the proxy for eth-api. Just use ETH_API_BASE_PATH

2023-11-03 07:25 UTC, DiRaiks commented on features/rewards/fetchers/rpcFetch.ts
> +  args: any[],
To get all rest arguments

2023-11-05 06:00 UTC, solidovic commented on features/home/stake-faq/list/how-can-i-get-steth.tsx
> +        <LocalLink
LocalLink already have <a> inside himself:
- https://github.com/lidofinance/ethereum-staking-widget/blob/37866bab2357e5d47b2830742f8abe78f394d156/shared/components/local-link/index.tsx#L29
- https://github.com/lidofinance/ethereum-staking-widget/blob/37866bab2357e5d47b2830742f8abe78f394d156/shared/components/link-ipfs.tsx#L26

other words everything is fine

**P.S. rechecked in infra mode  and IPFS mode**

2023-11-05 06:07 UTC, solidovic commented on shared/components/header/components/navigation/styles.tsx
> +export const NavLink = styled.span<{ active: boolean }>`
Source code made so that there is <a> tag in HTML output code (infra version or IPFS version it does not matter).
Based on this all native link operations not broken.

<img width="444" alt="image" src="https://github.com/lidofinance/ethereum-staking-widget/assets/9885789/4df228bb-f98e-4140-b880-6312b7763d57">

2023-11-05 06:15 UTC, solidovic commented on shared/components/switch/styles.tsx
> +export const SwitchItemStyled = styled.span<{ active: boolean }>`
same https://github.com/lidofinance/ethereum-staking-widget/pull/72#discussion_r1382513529

2023-11-08 09:37 UTC, solidovic commented on features/rewards/fetchers/rpcFetch.ts
> +  args: any[],
done

2023-11-08 09:40 UTC, manneredboor submitted a review, later dismissed

2023-11-08 09:48 UTC, DiRaiks approved these changes

2023-11-08 10:40 UTC, manneredboor submitted a review, later dismissed

2023-11-09 06:31 UTC, DiRaiks approved these changes

2023-11-20 09:39 UTC, Jeday commented on pages/_app.tsx
>        <Providers>
We have `Providers`. Can you move `CustomConfigProvider` inside and switch `providers` to named export

2023-11-21 10:52 UTC, solidovic commented on pages/_app.tsx
>        <Providers>
done

2023-11-21 13:03 UTC, Jeday submitted a review, later dismissed

2023-11-21 13:31 UTC, manneredboor approved these changes

2023-11-22 09:41 UTC, Jeday approved these changes

2023-11-22 09:53 UTC, merged