feat: add new matomo events
lidofinance/ethereum-staking-widget pull request #77
Opened 2023-10-06 13:45 UTC by solidovic

### Description

- Max button in withdrawals request form

### Code review notes

TODO

### Testing notes

TODO

### Checklist:

- [x] Checked the changes locally.
- [x] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-10-09 07:13 UTC, Jeday requested changes

2023-10-09 07:13 UTC, Jeday commented on shared/forms/components/input-decorator-max-button/input-decorator-max-button.tsx
> +    thisComponentInsideWithdrawalsRequestFormRef.current = true;
We can track this event in InputComponent much easier. Sure we might need additional onMax event handler. But that would be so much better than this.

2023-10-09 07:45 UTC, solidovic commented on shared/forms/components/input-decorator-max-button/input-decorator-max-button.tsx
> +    thisComponentInsideWithdrawalsRequestFormRef.current = true;
decided: use props drilling

2023-10-09 08:34 UTC, solidovic commented on shared/forms/components/input-decorator-max-button/input-decorator-max-button.tsx
> +    thisComponentInsideWithdrawalsRequestFormRef.current = true;
done

2023-10-09 08:54 UTC, DiRaiks commented on config/matomoClickEvents.ts
> -  calculateRewards = 'calculateRewards',
Why are you deleting this?

2023-10-09 09:02 UTC, DiRaiks approved these changes

2023-10-13 09:54 UTC, DiRaiks approved these changes

2023-10-13 11:18 UTC, itaven approved these changes

2023-10-13 13:30 UTC, closed without merging