feat: get 1inch rate on IPFS
lidofinance/ethereum-staking-widget pull request #82
Opened 2023-10-11 23:04 UTC by solidovic

### Description

### Demo

### Code review notes

### Testing notes

### Checklist:

- [ ] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-10-12 10:51 UTC, DiRaiks commented on config/one-inch.ts
> +export const API_LIDO_1INCH = `https://api-lido.1inch.io/v5.2/1/quote`;
Lets use the public endpoint.

2023-10-12 11:23 UTC, DiRaiks approved these changes

2023-10-12 12:48 UTC, Jeday requested changes

2023-10-12 12:48 UTC, Jeday commented on features/home/one-inch-info/components/one-inch-infs-ipfs.tsx
> +import { FC } from 'react';
typo in file name

2023-10-12 12:48 UTC, Jeday commented on features/home/one-inch-info/components/one-inch-info-not-ipfs.tsx
> +  const { data, initialLoading } = useLidoSWR<{ rate: number }>(
We don't need local endpoint anymore. You can delete /api/oneinch endpoint and just use the same as IPFS.

2023-10-12 12:48 UTC, Jeday commented on features/home/one-inch-info/hooks.ts
> +    standardFetcher,
Please add strategy(probably LAZY will be okay) like in other SWR requests. This will prevent spam and 429.

2023-10-12 12:48 UTC, Jeday commented on features/home/one-inch-info/hooks.ts
> +    standardFetcher,
Plus I think we use same endpoint as in withdrawals. Write custom swr  fetcher function, use  getOneInchRateApiUrl, in same fetcher do postcomute from memo below.  This will be much cleaner and faster.

2023-10-12 12:48 UTC, Jeday commented on config/one-inch.ts
> +  fromTokenAddress,
Why all of this in /config? Can we just move all 1inch related code to single module dedicated to it?

2023-10-13 08:40 UTC, solidovic commented on config/one-inch.ts
> +  fromTokenAddress,
We can move this code if will delete /api/oneinch endpoint

2023-10-13 09:00 UTC, solidovic commented on config/one-inch.ts
> +  fromTokenAddress,
Why we need store api url in different place (stake page and withdrawals req page)?

2023-10-13 09:33 UTC, solidovic commented on features/home/one-inch-info/hooks.ts
> +    standardFetcher,
ok. I will use STRATEGY_LAZY.

about: I think to use a `custom swr fetcher function` is overhead here.
in `features/withdrawals/hooks/useWithdrawalRates.ts` is occurs because of many code.

2023-10-13 09:37 UTC, Jeday commented on config/one-inch.ts
> +  fromTokenAddress,
My issue was request code in config file. Other stuff is ok.

2023-10-13 09:40 UTC, Jeday commented on features/home/one-inch-info/hooks.ts
> +    standardFetcher,
By `custom swr fetcher function` I mean an SWR with 
```
()=>{
  const rate = await get1inchrate(...)
  // code from memo
 // ...
  return {discount, ...}
}
``` 
So you can have SWR return directly everything you need without any extra hooks and react runtime overhead.

2023-10-20 05:33 UTC, Jeday approved these changes

2023-10-20 08:58 UTC, merged